### ISSUE TITLE
How to setup my dirvish_mode if I want both wildignore and sort ?

### ISSUE THREAD

**Issue by skywind3000** [justinmk/vim-dirvish#100]
Great plugin, I want to switch to dirvish from netrw, but there is only one question:

help dirvish:

```
g:dirvish_mode = 1                                  *g:dirvish_mode*
    Controls which files are listed and how they are presented.
    1:        'suffixes' and 'wildignore' determine sorting and visibility.
    2:        Shows all files, in the order returned by |glob()|.
    ":{cmd}": Ex-command |:execute|d after listing files.

    Mnemonic: higher number => more files.
```

and 

```
To make this automatic, set |g:dirvish_mode|: >
    let g:dirvish_mode = ':sort ,^.*[\/],'
```

It seems there is no way to setup `dirvish_mode` if I need wilddignore and sorting.
Is it possible to have both of them work together ?

**Comment by justinmk** [comment]
Hmm. Not sure if there's a nice way to do it, but `g:dirvish_mode` can be any arbitrary command(s).

**Comment by justinmk** [comment]
For reference, looks like you found a way to do this: https://github.com/justinmk/vim-dirvish/issues/101

**Comment by skywind3000** [comment]
Yes, I figured it out myself, but it is not a perfect solution,
still expecting the enhancement referenced in https://github.com/justinmk/vim-dirvish/issues/101
