### ISSUE TITLE
Annoying flicker when I open a new Dirvish buffer

### ISSUE THREAD

**Issue by skywind3000** [justinmk/vim-dirvish#101]
I'd like to have my filenames both sorted and filtered, so I write this config:

```VimL
function! s:setup_dirvish()
	if &buftype != 'nofile' && &filetype != 'dirvish'
		return
	endif
	let text = getline('.')
	exec 'sort ,^.*[\/],'
	let name = '^' . escape(text, '.*[]~\') . '[/*|@=]\=\%($\|\s\+\)'
	call search(name)
endfunc

augroup MyPluginSetup
	autocmd!
	autocmd FileType dirvish call s:setup_dirvish()
augroup END

let g:dirvish_mode = 0
```

This works fine, but there is a noticeable flicker when I open a new dirvish buffer, especially in a dir with a lot of files, because filenames was rendered unsorted at first, then it got sorted and rendered again in the vim window.

Filenames always got rendered twice, which lead to the annoying flicker.

I have tried to optimize it in the earlier step by g:dirvish_mode:

```VimL
function! DirvishSetup()
	let text = getline('.')
	for item in split(&wildignore, ',')
		let xp = glob2regpat(item)
		exec 'silent keeppatterns g/'.xp.'/d'
	endfor
	exec 'sort ,^.*[\/],'
	let name = '^' . escape(text, '.*[]~\') . '[/*|@=]\=\%($\|\s\+\)'
	call search(name)
endfunc

let g:dirvish_mode = 'call DirvishSetup()'
```

But the new setup code works worse, because filenames have been rendered three times:

1. first by dirvish itself, unfiltered and unsorted
2. filter by `DirvishSetup()`
3. sort by `DirvishSetup()`

-------
I love this tiny plugin, every thing works fine for me, but the flicker really sucks.

Is it possible to have the filenames both filtered and sorted before render to buffer ?
Can I setup a `g:dirvish_post_list_dir` hook to process the result from `s:list_dir()` in the way I like 
before passing them to `setline()` ?

Or, can I just have a `g:dirvish_mode = 3` to get filenames both sorted and filtered ?

If so, there is only one render needed, opening dirvish will become more elegant.

**Comment by justinmk** [comment]
@skywind3000 Thanks for the suggestions. A hook seems reasonable. 

Did you try `:set lazyredraw` (and _also_ `:set nolazyredraw`)?

Ultimately this is a n/vim bug, plugins shouldn't have to care about this.

**Comment by skywind3000** [comment]
my lazyredraw is always enabled but it still useless. Btw, I am using GVim

**Comment by justinmk** [comment]
@skywind3000 if you have Vim version with `win_execute`, can you check if flicker reduced after https://github.com/justinmk/vim-dirvish/pull/150 ?

**Comment by justinmk** [comment]
Closing for lack of followup.
