### ISSUE TITLE
Empty screen when re-enter the same directory

### ISSUE THREAD

**Issue by yous** [justinmk/vim-dirvish#102]
This is a minial vimrc to reproduce:

``` vimrc
set nocompatible

call plug#begin()
Plug 'justinmk/vim-dirvish'
call plug#end()
```

How to reproduce:
1. Open an existing file
2. Hit `-`
3. Re-open that file by hitting `Enter`
4. Hit `-`

Directories are properly displayed when I execute `:Dirvish %` at step 4.

Vim version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 28 2017 06:16:39)
macOS version
Included patches: 1-1350
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python            +vreplace
+conceal           +linebreak         -python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               +ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.2 -lobjc
```

**Comment by hauleth** [comment]
This can be resolved by refreshing view using `R` but this is annoying.

**Comment by hauleth** [comment]
This bug was introduced in latest commit 2c69d6c62c7212908f3f8db434b56b2992e27921, so pinning to 264ea014d302ea8b4c05c7bda072184a47395149 should temporarily solve the problem.

**Comment by justinmk** [comment]
Thanks all.

**Comment by dwayneyuen** [comment]
I still have this issue even though I have the latest update using `PlugUpdate`. Please let me know if you'd like more details.

**Comment by hauleth** [comment]
It seemed to be fixed for a while, but is still happening.

**Comment by justinmk** [comment]
Er... using the same steps as above? After restarting vim?

**Comment by dwayneyuen** [comment]
I've restarted vim, run `PlugUpdate`, and tried manually `git pull`ing in the plugin directory. I can replicate the behavior in multiple ways:
- Open file (`vi foo.txt`), back out of file with `-`, enter file with `<enter>`, back out again with `-`.
- Browse directory (`vi .`), back out of directory `-`, re-enter directory `<enter>`
- Browse directory (`vi .`), enter any folder `<enter>`, back out of directory `-`.

**Comment by justinmk** [comment]
If you change `s:buf_modified()` to return `0` is the problem fixed?

https://github.com/justinmk/vim-dirvish/blob/202e37dce540d648c5f113c217c95085cd41c0a9/autoload/dirvish.vim#L126

**Comment by dwayneyuen** [comment]
Making the change to `buf_modified` fixes the issue.

Running those commands:
```
:echo b:dirvish
{'altbuf': -1, '_dir': 'DIR_NAME_WAS_HERE', '_c': 5, 'prevbuf': 1}
echo b:changedtick
24
```

**Comment by yous** [comment]
Here's mine:
```
:echo b:dirvish
{'altbuf': -1, '_dir': '/path/to/dir/', '_c': 3, 'lastpath': '/path/to/dir/file', 'prevbuf': 1}
:echo b:changedtick
4
```

Changing `s:buf_modified()` makes `_c` and `b:changedtick` to be the same.

**Comment by justinmk** [comment]
Oh, do you have 'hidden' option set ?

**Comment by hauleth** [comment]
No. I like behaviour of `nohidden`. 

--
Łukasz Jan Niemier

**Comment by dwayneyuen** [comment]
I don't have hidden set either

**Comment by justinmk** [comment]
If you have `:autocmd FileType dirvish ...` handlers setup, can you show them here? Also are you using `g:dirvish_relative_paths=1` ?

**Comment by dwayneyuen** [comment]
I have:
```
autocmd FileType dirvish silent keeppatterns g@\v/.*\.o|.*\.pyc|.*\.so/?$@d
let g:dirvish_relative_paths = 0
```

I can replicate the behavior with both of these commented out, or with `g:dirvish_relative_paths` set to 1.

**Comment by justinmk** [comment]
Does 17ee209a12884dd6c4c89482b223962a32279389 help?

**Comment by justinmk** [comment]
Could you put `:echom b:changedtick` at the beginning of `s:do_open()`, to see if it changes somewhere after that?

**Comment by justinmk** [comment]
thanks, but we also need to know `:echo b:dirvish b:changedtick` after the buffer is loaded (i.e., do it at the `:`-prompt). Else there's nothing to compare it. Sorry that wasn't clear.

**Comment by dwayneyuen** [comment]
Ah, gotcha.

1) `vi .` - before: 2, after:
`{'altbuf': -1, '_dir': '/Users/dwayneyuen/', '_c': 4, 'prevbuf': -1} 4`
2) `-` - before: 4, after:
`{'altbuf': -1, '_dir': '/Users/', '_c': 3, 'lastpath': '/Users/dwayneyuen/', 'prevbuf': 1} 3`
3) `<enter>` - before: 3, after:
`{'altbuf': -1, '_dir': '/Users/dwayneyuen/', '_c': 4, 'prevbuf': 1} 5`

**Comment by dwayneyuen** [comment]
I'm running on MacOS High Sierra.

**Comment by justinmk** [comment]
I can repro it. Will take a look.

**Comment by justinmk** [comment]
Even with `hidden`, vim unloads a `nobuflisted` (or maybe `buftype=nofile`) buffer if it is not showing in a window.

**Comment by dwayneyuen** [comment]
https://github.com/justinmk/vim-dirvish/commit/e4b3c4b62d0ddb2d24aa8f9fcf3820f6d6de4ebf fixes the issue for me. Thanks for your help and the amazingly quick turnaround!
