### ISSUE TITLE
Bindings stopped working in dirvish buffer

### ISSUE THREAD

**Issue by shmup** [justinmk/vim-dirvish#103]
It is incredibly bizarre to me.

I press `-` and can navigate up and down but pressing `return` just moves cursor to the next line. `q` will not close this buffer.

I'm using vim8 and no vimrc to narrow things down. This is even the only plugin loaded, heh.

A weird thing is: this was working fine earlier today, so mostly I feel like the error may be on my part.

**Comment by justinmk** [comment]
> I'm using vim8 and no vimrc to narrow things down

Should be easy to reproduce then. Can you say the exact steps

**Comment by shmup** [comment]
I've got nothing to report back, really. Except this simple sanity check:

```
mkdir -p .vim .vim/pack/plugins/start
cd .vim/park/plugins/start
git clone https://github.com/justinmk/vim-dirvish.git
```
From there I run vim, press `-`, see the directory listing, and face the scenario stated in issue above.

```
$ brew upgrade vim
Error: vim 8.0.1400_1 already installed
```

That's my specific vim version.

**Comment by shmup** [comment]
Here I am reporting back that I tried it again and it's fine and man, I _do not understand_.
