### ISSUE TITLE
Dont override previous mapping

### ISSUE THREAD

**Issue by davidsierradz** [justinmk/vim-dirvish#105]
Hi, I am using this to not override a previous mapping:

`~/.local/share/nvim/plugged/vim-dirvish/ftplugin/dirvish.vim`

``` viml
if mapcheck('<C-P>', 'n') == ""
    execute 'nnoremap '.s:nowait.'<buffer><silent><unique> <C-p> <C-\><C-n>k:call feedkeys("p")<CR>'
endif
```

Do not know if this is the right way to do it, obviously this will interfere with future updates.

**Comment by justinmk** [comment]
@davidsierradz Ok, but if we did that for all mappings the mappings available in a Dirvish buffer would be random, based on whatever global mappings the user happens to have, irrespective of whether those global mappings make any sense at all in a Dirvish buffer.

The usual way around this is to provide `<Plug>(dirvish_foo>` maps and skip the default `<C-p>` if the user mapped something else to the `<Plug>...` variant. I guess I'll have to do that.

**Comment by justinmk** [comment]
@davidsierradz see https://github.com/justinmk/vim-dirvish/commit/197afdfdf1d837cbebf31f699bdefe2cff64073a#diff-0147afd173246b6a747041e190ecba63R178 for a way to do this.
