### ISSUE TITLE
exists("#User#Fugitive") returns 1 even if vim-fugitive is not installed.

### ISSUE THREAD

**Issue by amsayk** [justinmk/vim-dirvish#108]
I don't have vim-fugitive but vim-dirvish keeps showing `Unknown function: fugitive#detect` error.

Turns out (for me at least), exists("#User#Fugitive") always returns 1.

I propose using exists("*fugitive#detect").

I will send you a PR.

**Comment by justinmk** [comment]
> Turns out (for me at least), exists("#User#Fugitive") always returns 1.

Can't reproduce that with `vim -u NORC -N`, but `exists("*fugitive#detect")` makes sense anyway.

**Comment by justinmk** [comment]
> Turns out (for me at least), exists("#User#Fugitive") always returns 1.

Can't reproduce that with `vim -u NORC -N`.

`#User#Fugitive` was chosen to future-proof if/when fugitive moves to an autoloaded model (in which case, `exists("*fugitive#detect")` would return false on startup, etc.).

Can you try `exists('#fugitive')` ?
