### ISSUE TITLE
Default search not empty

### ISSUE THREAD

**Issue by AmaruCoder** [justinmk/vim-dirvish#111]
Thank you for writing this amazing plugin. For me, it has replaced NerdTree and netrw. However, after opening a folder, and try to find a file using the search option (/), it is already preloaded with: `\ze[^\/]*[\/]\=$ `. How can I change that to empty?

**Comment by justinmk** [comment]
Glad you like it!

If the search is empty it will match concealed text, which you almost certainly don't want. 

See also #28

See also

**Comment by AmaruCoder** [comment]
Oceanside, March 03, 2018

Dear Justin,

Thank you for the prompt reply, and, again, for writing this plugin.
	Cordially,

José

**Comment by justinmk** [comment]
@duganchen don't do anything, just start typing ...

**Comment by duganchen** [comment]
But if I just start typing, then when I want to search for appears to the left of the "\ze[^/]*[/]=$" string, and that string ends up being part of the pattern being searched for.

**Comment by virus-found** [comment]
Frankly I've always thought it was a bug.
Any workaround possible nowadays?

**Comment by duganchen** [comment]
Document it better? ;)

**Comment by virus-found** [comment]
> Document it better? ;)

It looks as if it's terribly borked. I'm sure the docs will not redeem it.

**Comment by justinmk** [comment]
> It looks as if it's terribly borked.

You mean it looks weird and you don't understand it, so it's "borked"? Or what do you mean exactly?

You can unmap it if you don't want it:

    au FileType dirvish silen! unmap <buffer> /

**Comment by virus-found** [comment]
No offence meant.
I wanted to say my opinion only: this behaviour looks and feels wrong. I've always thought it was either a bug or caused by one of my many tweaks in .vimrc, but was too lazy to figure out.
