### ISSUE TITLE
ctrlp dirvish

### ISSUE THREAD

**Issue by bbtdev** [justinmk/vim-dirvish#112]
Hello,

I'm no power user, so maybe this is a dumb request, but I do really love dirvish and I really love ctrlp. Is it possible to use ctrlp inside a dirvish window/buffer?

**Comment by justinmk** [comment]
I have no idea, I don't use ctrlp. Why wouldn't it be possible?

**Comment by bbtdev** [comment]
Ops, sorry didn't formulate properly.
ctrlp is not working inside dirvish, this was more of a feature request :). But since you don't use, it is unlikely will it happen, no?

P.S.: Love your plugin btw

**Comment by justinmk** [comment]
did you report to ctrlp?

**Comment by bbtdev** [comment]
Yes, they have 152 issues open, so fingers crossed :)

**Comment by vimeitor** [comment]
Why don't you add a mapping?

` autocmd FileType dirvish nnoremap <buffer><silent> <c-p> :CtrlP<cr>`

**Comment by bbtdev** [comment]
Wow, so that was the problem the key mapping.
Damn, thank you!
