### ISSUE TITLE
Set `nospell` while inside a dirvish buffer

### ISSUE THREAD

**Issue by chaucerbao** [justinmk/vim-dirvish#115]
Just wondering what you think about setting `nospell` when entering a dirvish buffer, and restoring the previous setting upon leaving.

![image](https://user-images.githubusercontent.com/794434/39087703-c45d4d4e-4559-11e8-9338-d7a71c0076b4.png)

**Comment by justinmk** [comment]
Attempted and later removed in f8bb56fe7f85. For a plugin, trying to micro-manage window options in Vim is generally a disaster.

It's trivial to do this if you really care.

    au FileType dirvish setlocal nospell

**Comment by chaucerbao** [comment]
Makes sense. And thank you for an alternate solution.
