### ISSUE TITLE
Error when loading dirvish (Expected buffer name)

### ISSUE THREAD

**Issue by joshaw** [justinmk/vim-dirvish#12]
I'm not sure what to title this error, also not sure about how to debug it.

I'm getting the message:
```
Error detected while processing function dirvish#open..5:
line      62:
expected buffer name: "C:\home\username\vimfiles\" (actual: "")
```
when loading dirvish from my vimrc file. I notice that line [160](https://github.com/justinmk/vim-dirvish/blob/master/autoload/dirvish.vim#L160-L163) in `autoload/dirvish.vim` is where this error is thrown from, where your comment suggests that this is a bug.

Some things that might be contributing:
- This is under Windows (dirvish works absolutely fine in the vast majority of  use cases)
- This occurs reliably when pressing `-` to load dirvish from within my vimrc
- My vimrc is in a folder called vimfiles, which itself is a symlink (I think  this might be the root cause) to my `.vim/` folder (so I can use the same  folder for Windows/Cygwin/Linux.

Anything else I can provide to debug, just let me know. Thanks for this very helpful and much used plugin.

**Comment by justinmk** [comment]
@joshaw Thanks for the report, I've noticed some quirks on Windows too, though it's been solid for several months. I have been waiting until I migrate to a non-dictionary functions in the plugin source, to make step-by-step debugging possible. I'll take this as motivation to do that now.

> My vimrc is in a folder called vimfiles, which itself is a symlink

By symlink to you mean a windows junction (?) created by `mklink`? 

> .vim/ folder (so I can use the same folder for Windows/Cygwin/Linux.

I used to do that too, now I just do this:

```vim
  if has('vim_starting') && s:is_windows
    set runtimepath+=~/.vim/
  endif
```

No need for symlinks now, `_vimfiles/` is just a bad memory.

Glad you like the plugin!

**Comment by joshaw** [comment]
I did use `mklink` but the documentation says
```
MKLINK [[/D] | [/H] | [/J]] Link Target
        /D      Creates a directory symbolic link.  Default is a file symbolic link.
        /J      Creates a Directory Junction.
```
and I used `/D` without `/J`, so not entirely sure what I've created.

> No need for symlinks now

I have tried that in the past, but I like to keep my vimrc and nvimrc files inside the .vim folder to make version control easier, so there'd need to be symlinks somewhere, either between files, or folders.

I've been playing around with making my own directory browser (simply because. Also I enjoy stripping plugins back to the absolute basics while still being functional) [navd](https://github.com/joshaw/vim/blob/master/autoload/navd.vim) (for want of a better name) which is implemented very naively, but I haven't yet run into any issues, it seems to "just work". I don't know why dirvish might have problems where I didn't, but thought it worth pointing out.

Cheers.

**Comment by LemonBoy** [comment]
It seems the latest commits (one of the two most recent ones) made dirvish fail with this error when opening any folder.
I've currently frozen the plugin at the revision `ae206266555ff3e81db9f45fa54dbcb3a1a07a49`, the latest version that doesn't trigger this bug.

**Comment by justinmk** [comment]
Thanks, I noticed it too on some systems.
