### ISSUE TITLE
No such group or event: TextChanged,TextChangedI

### ISSUE THREAD

**Issue by tjharman** [justinmk/vim-dirvish#120]
Hi,

If I try and use dirvish under linux on this VIM Version:

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jul 18 2017 04:12:04)
Included patches: 1-547
Extra patches: 8.0.0707, 8.0.0706, 8.0.0703, 8.0.0378, 8.0.0377, 8.0.0322, 8.0.0056
```

I get the following error:

```
Error detected while processing function dirvish#open..<SNR>44_open_dir..<SNR>44_buf_init:
line    4:
E216: No such group or event: TextChanged,TextChangedI <buffer> if <SID>buf_modified()&& has('conceal')|exe 'setlocal conceallevel=0'|endif
```

The readme says it should work on vim 7.2+. is that still true?

It seems to work on later versions of VIM for me, on different Debian versions (with more recent versions of VIM)

I'm fairly sure this used to work a year or so ago.

**Comment by justinmk** [comment]
@tjharman Thanks for reporting. 7.2 is definitely still supported, though I depend on bug reports for that purpose.

**Comment by tjharman** [comment]
Thanks very much, can confirm the latest revision fixes the issue for me and I can use dirvish again!

Cheers,
Tim
