### ISSUE TITLE
Open vertical split of current file path

### ISSUE THREAD

**Issue by rawaludin** [justinmk/vim-dirvish#121]
In netrw, if I press `:Ve` when no file open, it will open project root in vertical. If I invoke that while having an open file, it will open current file folder. Is it possible to achieve that using dirvish?

I'm using this

```
command! -nargs=? -complete=dir Vexplore leftabove vsplit | silent Dirvish <args>
```

But when I use `:Ve` it open the root directory, not the current file directory like `-`. 
Is it possible to do that?

**Comment by justinmk** [comment]
> But when I use :Ve it open the root directory

`:Dirvish %` works local to file;  `:Dirvish` works local to CWD.

You can use `:Vexplore %` or change your command definition:

    command! -nargs=? -complete=dir Vexplore leftabove vsplit | exe 'silent Dirvish '.(empty('<args>')?'%':'<args>')
