### ISSUE TITLE
Is it possible to skip shdo window?

### ISSUE THREAD

**Issue by rawaludin** [justinmk/vim-dirvish#122]
Hi, thanks for the plugin! :)

I use the shdo for renaming file. Is it possible to skip shdo window at all? 
So after typing `:Shdo mv {} new-name.json` the command just executed.

I already sure my command is correct and showing shdo window just add more step to simple command.

If its not possible, feel free to close this issue.
Thanks!

**Comment by justinmk** [comment]
No, but did you try `Z!` in the shdo window?

**Comment by rawaludin** [comment]
Yes. That's work. I just don't want to show that window at all. I want
dirvish to execute my command immediately after I press return on command
line.

**Comment by justinmk** [comment]
A temporary cmdline mapping seems to work:

    :cnoremap <CR> <CR>:call feedkeys('Z!')<CR>

Then unmap it on `CmdLineLeave` (this is a new event in Vim 8.1 / Nvim 0.3).

Other than that, this is not a use-case I want to optimize for. Making potentially destructive changes easy to do is something netrw is good at.
