### ISSUE TITLE
Support for vim-devicons?

### ISSUE THREAD

**Issue by pkazmier** [justinmk/vim-dirvish#126]
I was looking for some ideas on how to create a vim-devicons plugin to Dirvish. Integrating devicons comes down to invoking one function that takes a filename which then returns a character from the font that represents the file type. Not being familiar with vim script, I started reading docs and looking at the Dirvish git plugin for ideas. It seems like the way to implement this is to dynamically create syntax rules that can conceal the directory path and use the output of the above function as the cchar. The problem is that a syntax rule is needed for every possible file type in the directory. I’m not sure if that’s an abuse of what the syntax facility was meant to provide. Overall, this approach seems like a hack to me.

Are there any facilities in neovim that allow one to conceal arbitrary pieces of text by position in the buffer? Or can it only be done via syntax rules? I know in Elisp-land, the have the concept of an overlay which can essentially attach properties to text in the buffer. One of the properties you can attach is arbitrary text (among all sorts of other things), which shows up on the screen, but not in the actual contents of the buffer. Something like that would work great here as I understand one of the goals of Dirvish is that the line in the buffer is just a plain-old filename for simplicity’s sake. Does neovim have any other way of annotating the text in a buffer without modifying the actual text?

I assume you’ll have similar issues if you want to provide that tree view with anything other than pure whitespace as mentioned in another issue. Do you have any other suggestions that I might pursue?

**Comment by justinmk** [comment]
> Are there any facilities in neovim that allow one to conceal arbitrary pieces of text by position in the buffer?

https://github.com/neovim/neovim/pull/8180 works towards that (see the discussion about offset instead of only EOL).
