### ISSUE TITLE
[Enhancement] Context menu with actions

### ISSUE THREAD

**Issue by kristijanhusak** [justinmk/vim-dirvish#128]
Hi,
would you be interested in adding a context menu that helps executing most common tasks? Similar to NERDTree menu when you press M. Maybe something like this:

Selection option:
![select](https://i.imgur.com/NvP9BTk.png)
Enter:
![enter](https://i.imgur.com/HAK3xXV.png)
Confirm:
![confirm](https://i.imgur.com/5pW5JeV.png)

I made a prototype (from screenshots), but i would make a PR with more robust and extendable solution.

**Comment by justinmk** [comment]
No, that is pretty much the antithesis of the plugin :)

**Comment by kristijanhusak** [comment]
Yeah, of course i did, and i used it until now, but i think it requires much more effort than it should.
Ok, i guess i'll create it only for myself, or as a separate plugin.
Thanks.

**Comment by kristijanhusak** [comment]
For the bulk actions, i agree completely, but most of the time that's not used.
I'm missing few things that do not exist out of the box in vim or sh:
* Creating file in non existing nested folder. Basically `mkdir -p my/sub/path && touch my/sub/path/myfile.txt`
* As you said, renaming and moving. Most of renaming for me is just adding or removing part of the file name. `Shdo` requires me to write the whole file name.
* `Z!` mapping is really hard to press on English keyboard (shift + z + 1)

These are definitely not a big issues, i even consider it nitpicking, but it's still nice to have if someone wants it.

**Comment by justinmk** [comment]
> Creating file in non existing nested folder.

I use this autocmd: https://github.com/justinmk/config/blob/91c792a4f75d9200944f8e21863ea03eaee4e3c1/.config/nvim/init.vim#L1180

Then this works automatically, even if `foo/bar/` path doesn't exist:

    :e foo/bar/baz.txt
    :w

> Shdo requires me to write the whole file name.

`x` prefills the command, and `{}` substitutes the filename.

    :Shdo mv {} {}<CR>
    <use normal-mode commands to edit the target name>
    Z!

No menus, no wizards, full control.

> Z! mapping is really hard to press on English keyboard 

I use US layout, it's quite easy. Hold the right-hand shift key...

The mnemonic for `Z!` is Vi's `ZZ` / `ZQ` commands, which are also much easier to type than `:w<CR>` / `:q<cr>`.

**Comment by kristijanhusak** [comment]
Nevermind, i won't create it. Thanks for your help!
