### ISSUE TITLE
Curly braces in path names cause dirvish to fail showing directory contents

### ISSUE THREAD

**Issue by ohcibi** [justinmk/vim-dirvish#135]
I have directories which's names have curly braces `{{..}}` in them. When I try to enter those using dirvish neovim is irresponsible for a few seconds and then just shows an empty buffer with `ft=dirvish`

## Reproduce

```sh
# Isolate plugin
mkdir $HOME/dirvishtest
cd $HOME/dirvishtest
echo 'set packpath=$HOME/dirvishtest' > vimrc
mkdir -p pack/dirvish/start
git clone https://github.com/justinmk/vim-dirvish pack/dirvish/start/vim-dirvish

# Create test case
mkdir \{\{foo\}\}
touch \{\{foo\}\}/test-in-foo
touch test

# Reproduce the error
nvim -u vimrc -i noshada test
## Now press `-` to open dirvish. The directory '{{foo}}' is listed. Navigate to it and hit enter.
```

After that I'd expect vim to show the `test-in-foo` file but instead an empty buffer is shown. The filetype of that buffer is `dirvish`.

## `:version`

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-
fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/config -I/tmp/n
eovim-20190113-94620-d8vv4n/neovim-0.3.4/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190113-94
620-d8vv4n/neovim-0.3.4/build/src/nvim/auto -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.4/share/nvim"
```

**Comment by justinmk** [comment]
Works for me with `NVIM v0.3.4` on macOS 10.13.6.

> After that I'd expect vim to show the `test-in-foo` file but instead an empty buffer is shown. The filetype of that buffer is `dirvish`.

What does `:echo bufname('%')` report at this step?

Also just a guess, but what `:set isfname?` report? From `:help dirvish-faq`:

```
Why does Dirvish report "invalid directory" for a path that contains unusual
characters (e.g. brackets "[]")? 

Check your 'isfname' setting. On Windows (where filepaths may contain
backslashes "\") fnamemodify() may produce nonsense if 'isfname' does not
contain the aforementioned unusual characters.
```

**Comment by ohcibi** [comment]
`:echo bufname('%')` is `/Users/ohcibi/test/curlytest/{{curlydirectory}}/` and in fact `set isfnam` did not contain `{,}`. I tried to add those by adding

    set isfname+=\{,\}

to the beginnig of my vimrc before dirvish gets loaded but that didn't help. Also dirvish is not complaining 'invalid directory' or anything else. It silently opens an empty buffer with said name.

**Comment by justinmk** [comment]
Since I can't reproduce it there's nothing I can do. You could add debugging statements to `s:list_dir()` to see what's going on.

```diff
diff --git a/autoload/dirvish.vim b/autoload/dirvish.vim
index 5c77dd1e14d9..b679cb185cbe 100644
--- a/autoload/dirvish.vim
+++ b/autoload/dirvish.vim
@@ -340,6 +340,7 @@ function! s:buf_render(dir, lastpath) abort
     setlocal undolevels=-1
   endif
   silent keepmarks keepjumps %delete _
+  echom string(s:list_dir(a:dir))
   silent keepmarks keepjumps call setline(1, s:list_dir(a:dir))
   if type("") == type(get(g:, 'dirvish_mode'))  " Apply user's filter.
     execute get(g:, 'dirvish_mode')
```

If that prints `[]` (empty list), then the next step is to try the statements inside of `s:list_dir()` to see what's wrong.

**Comment by justinmk** [comment]
@ohcibi is this still an issue, and have you been using that patch without any problems?

**Comment by ohcibi** [comment]
@Justinmk since from my point of view the patch I pasted fixes an obvious error which must happen on your system as well but you still can’t reproduce I wouldn’t count on that patch. Have you by any chance tried to test and see if the globbing on its own behaves differently than I described, on your system?

**Comment by justinmk** [comment]
> Have you by any chance tried to test and see if the globbing on its own behaves differently than I described, on your system?

Not sure what you mean, I tried/failed to reproduce it.  Can you try these steps, or tell me what changes are needed in these steps to reproduce the issue:

```
mkdir \{\{foo\}\}
touch \{\{foo\}\}/test-in-foo
touch test

nvim
:echo glob(substitute('{{foo}}/','\V[','[[]','g').'*',1,1)

['{{foo}}/test-in-foo']
```

**Comment by ohcibi** [comment]
> Do you see ['{{foo}}/test-in-foo'] in the final step?

No I don't and this what I mean by asking if you have been able to reproduce it. Apparently this works different on your system as I need to explicitly escape the `{}` to get `['{{foo}}/test-in-foo]'`, i.e. `:echo glob(substitute('\{\{foo\}\}/', '\V[', '[[]', 'g').'*',1,1)`. This is basically what my patch does. But it calls substitute twice because I was unable to use it properly. If theres no other way to do it, I'll PR it.

**Comment by neocryses** [comment]
I too had exactly the same problem as ohcibi and applying his patch to the function `s:list_dir(dir)` fixed the issue for me.

The path which I had problem with was the following:
`/Users/neocryses/Projects/cookiecutter-pypackage/{{cookiecutter.project_slug}}`
