### ISSUE TITLE
K does not show symlink information for directories

### ISSUE THREAD

**Issue by arecarn** [justinmk/vim-dirvish#138]
https://github.com/justinmk/vim-dirvish/blob/d33796c460229b2cf0dd09fedf1b272da9d13a42/autoload/dirvish.vim#L72

I noticed for symlinked directories K does not print the link information.

I played around with getftype() and noticed for symlinked directories when the trailing '/' in the name is removed it returns 'link' otherwise it returns 'dir'.

**Comment by justinmk** [comment]
Good observation, thanks!
