### ISSUE TITLE
Pressing / selects everything

### ISSUE THREAD

**Issue by chalmagean** [justinmk/vim-dirvish#141]
Not sure why, when I press `/` in a dirvish buffer, the search pattern is `\ze[^\/]*[\/]\=$`.

**Comment by justinmk** [comment]
The workaround is to simply press another key, i.e., actually search for something.

`\ze[^\/]*[\/]\=$` is pre-filled to avoid matching the full path (concealed text). Without it, `/foo` would match `/foo/bar/baz` even though `/foo/bar/` is concealed in the buffer.  See also https://github.com/justinmk/vim-dirvish/pull/28.


Vim's `'incsearch'` matches zero-width expressions. Nothing can be done about that.
