### ISSUE TITLE
E121: Undefined variable: w:dirvish when using :new +Dirvish

### ISSUE THREAD

**Issue by tammersaleh** [justinmk/vim-dirvish#142]
When using the minimal vimrc below (and after running `:PlugUpdate`), the `:Dirvish` command works fine, but `:new +Dirvish` gives the error `E121: Undefined variable: w:dirvish`

``` vimscript
set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'https://github.com/justinmk/vim-dirvish'
call plug#end()
```

**Comment by tammersaleh** [comment]
I can also trigger it by first typing `:new`, and then `-`.

It also looks like `:split +Dirvish` works fine, which is a good workaround for me.

**Comment by tammersaleh** [comment]
I also seem to get this error when running `:split +Dirvish` from a quickfix location window.

**Comment by justinmk** [comment]
Cannot reproduce. Did you restart vim after running `:PlugUpdate` ?

Are you sure no other plugins are loaded?  `:scriptnames` should only show stuff that is shipped with vim.

I tested with Nvim 0.4 and Vim 8.1.1005:

    vim -u DEFAULTS -N +":set rtp+=~/.config/nvim/pack/minpac/start/vim-dirvish/" +":runtime plugin/dirvish.vim"
    nvim -u NONE +":set rtp+=~/.config/nvim/pack/minpac/start/vim-dirvish/" +":runtime plugin/dirvish.vim"

**Comment by markonm** [comment]
I can reproduce this with Vim 8.1.1561. 
```
echo "test" > test && vim --clean "+ set packpath+=.vim | packadd vim-dirvish | e test | new | norm -"
```

**Comment by trsdln** [comment]
I'm experiencing similar issue.


Steps to reproduce:

1. Open Vim: `vim -u DEFAULTS -N +":set rtp+=~/.vim/bundle/vim-dirvish/" +":runtime plugin/dirvish.vim"`
2. Create split: `:vsplit`
3. Open arbitrary file: `:e some-file.txt`
4. Go back to empty window: `C-W l` 
5. Try to open Dirvish: `-`

Then this error is shown:

![image](https://user-images.githubusercontent.com/6911494/59836509-50952b80-9354-11e9-885e-950187332213.png)

Vim 8.1.1450, macOS 10.14.5

**Comment by justinmk** [comment]
What does this say:

    :set hidden?

**Comment by trsdln** [comment]
`hidden`

**Comment by hkupty** [comment]
I've got the same error essentially every time I open a file then`:vspl | wincmd l | enew | normal -`.

`:set hidden?` returns `hidden` for me.

**Comment by justinmk** [comment]
For everyone here, this is happening in `tab_win_do` ? Only 1 backtrace was reported.
