### ISSUE TITLE
Lexplore command?

### ISSUE THREAD

**Issue by pablopunk** [justinmk/vim-dirvish#143]
Hi, I just installed `vim-dirvish` today, so I'm a noob :)

I currently use `:Lexplore` with `netrw` to toggle the left side explorer. In dirvish docs I can see how to use Explore/Sexplore/Vexplore but not Lexplore, is it possible to make it work?

**Comment by justinmk** [comment]
Lexplore is a "project drawer" thing. It is not really necessary. Just use `p` and `ctrl-n`/`ctrl-p` in Dirvish.
