### ISSUE TITLE
Disallowing q makes it impossible to open command line window

### ISSUE THREAD

**Issue by comicsads** [justinmk/vim-dirvish#146]
A little more than a week ago, the `q` command in dirvish was deprecated in favor of using `gq` to return to the original file. I didn't even know this command existed personally, I only used `q` to access the command line window `q:` which is supposed to open a window with recently used commands that you can edit as you would a text file in vim. I found a workaround where typing `:<C-f>` will open the same window, but I think it would be better to leave q as it operates in normal mode.

**Comment by justinmk** [comment]
This is a strange report because `q` has always been mapped. Morever, the entire purpose of https://github.com/justinmk/vim-dirvish/commit/cfc66aa4486c911f4e6f802e0636c94d013952c7 is to prepare to remove the `q` mapping, so that `q:` and other builtin uses of `q` (macros) are available.

**Comment by comicsads** [comment]
I don't know, I remember being able to use `q:` before. I guess I'll close this issue, as I just wanted to make sure you were aware of this
