### ISSUE TITLE
Open in new tab keybinding?

### ISSUE THREAD

**Issue by rgrinberg** [justinmk/vim-dirvish#15]
I know the dirvish help doc states how to accomplish this but I'm wondering why it's not available by default. Seems like this is basic functionality, would you accept a PR to add this mapping by default?

**Comment by justinmk** [comment]
Map it to what? I could not find a good map, that's why I punted. :)

**Comment by rgrinberg** [comment]
In docs, you've used `t`. Is there anything wrong with that mapping?

**Comment by justinmk** [comment]
It conflicts with normal function of t, which is annoying. 

Very soon I'll be tightening up the API so that dirvish#open() can be used to get the expected functionality.

**Comment by justinmk** [comment]
See https://github.com/justinmk/vim-dirvish/blob/master/doc/dirvish.txt#L90-L92 for a more robust way to achieve this (handles multiple selections; change the `0` to `1` for "background" behavior).
