### ISSUE TITLE
Error when 'shell' contains a space

### ISSUE THREAD

**Issue by gpanders** [justinmk/vim-dirvish#152]
If `'shell'` has a space in it (e.g. `set shell=/usr/bin/env\ bash`), Shdo fails with the following:

```console
bash: /usr/bin/env bash: No such file or directory

shell returned 127
```

This is due to the call to `shellescape(&shell)` in the [Z! mapping](https://github.com/justinmk/vim-dirvish/blob/master/autoload/dirvish.vim#L139) which converts `/usr/bin/env bash` into `'/usr/bin/env bash'`, where it is interpreted as a single command.

One possible solution is to change `shellescape(&shell)` to `join(map(split(&shell), 'shellescape(v:val)'))`. This converts `/usr/bin/env bash` to `'/usr/bin/env' 'bash'` which is interpreted by the underlying shell just fine. This should also continue to escape any of the characters that `shellescape` originally intended to escape.

If this solution is satisfactory I will create a PR.

**Comment by justinmk** [comment]
It is not valid to set `shell` to an arbitrary command with arguments. What is Vim (or dirvish) supposed to do when the path to arg0 contains spaces?

Also what's the point of use `env bash` ? Simply `bash` will use your environment already.

**Comment by gpanders** [comment]
Fair enough.

> Also what's the point of `env bash` ? Simply `bash` will use your environment already.

I use fish and simply cribbed it from [vim-sensible](https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim#L72). But you're right of course.

**Comment by justinmk** [comment]
Hmm. If vim-sensible does it that suggests Vim has some hacks to make this work, and thus vim-dirvish should consider supporting it also.

Vim and Neovim have had lots of PR work in the last year related to dealing with 'shell' spacing edge-cases, which hints that the mountain of hacks is an ongoing source of problems...

**Comment by gpanders** [comment]
> Hmm. If vim-sensible does it that suggests Vim has some hacks to make this work, and thus vim-dirvish should consider supporting it also.
> 
> Vim and Neovim have had lots of PR work in the last year related to dealing with 'shell' spacing edge-cases, which hints that the mountain of hacks is an ongoing source of problems...

The commit that added that change to vim-sensible is [here](https://github.com/tpope/vim-sensible/commit/7f46e82fc7e343be84df6c06bec63dd6494b6712) and [this](https://github.com/tpope/vim-sensible/pull/156) is the corresponding issue. It looks it was changed from `bash` to `/usr/bin/env bash` to support BSD systems, although I agree with what you said earlier that simply using `bash` would be sufficient as far as I can tell.

**Comment by justinmk** [comment]
> One possible solution is to change `shellescape(&shell)` to `join(map(split(&shell), 'shellescape(v:val)'))`. This converts `/usr/bin/env bash` to `'/usr/bin/env' 'bash'` which is interpreted by the underlying shell just fine. This should also continue to escape any of the characters that `shellescape` originally intended to escape.
> 
> If this solution is satisfactory I will create a PR.

If you are still willing to send a PR I think this is worth trying.

**Comment by gpanders** [comment]
I just use `shell=/bin/sh` now so not an issue for me, but for the sake of typing up old loose ends I'll send a PR :)
