### ISSUE TITLE
Error opening Dirvish

### ISSUE THREAD

**Issue by ironfish** [justinmk/vim-dirvish#154]
Getting the following error message when opening Dirvish. This never happened until I upgrade Neovim to 0.4.3.

```
Error detected while processing function dirvish#open[39]..<SNR>100_open_dir[43]..<SNR>100_buf_render:
line 16:
E21: Cannot make changes, 'modifiable' is off: silent keepmarks keepjumps %delete _
```

**Comment by justinmk** [comment]
Obviously doesn't happen for me, so you need to narrow down the minimum parts of your config that lead to this . Looks like you have 100 plugins?

**Comment by ironfish** [comment]
Not sure where you got the idea I have over 100 plugins. In any case I made some changes and will test again.

**Comment by justinmk** [comment]
> Not sure where you got the idea I have over 100 plugins

`<SNR>100_open_dir` in the error message indicates that 100 scripts were sourced in that session, which typically means 100 plugins are installed. 

And dirvish was number 100 in this case, so 99 other plugins could be doing funny things. You must narrow down the issue by disabling half of your plugins successively.
