### ISSUE TITLE
"." is a directory

### ISSUE THREAD

**Issue by nomasprime** [justinmk/vim-dirvish#155]
Just upgraded everything and I started getting this message when I use `nvim .` from shell.

Not sure if it's a Dirvish or NeoVim thing but do you know how I can make it go away and avoid the extra key stroke every time?

**Comment by nomasprime** [comment]
After further testing doesn't look like it's a Dirvish issue.

**Comment by justinmk** [comment]
@nomasprime Thanks for the followup! That would indeed be a very strange issue (which I can't reproduce)
