### ISSUE TITLE
Enable `q` in .vimrc

### ISSUE THREAD

**Issue by virus-found** [justinmk/vim-dirvish#157]
Hi and thanks for the wondrous plugin!

I am looking for a *simple way* to enable _q_ to _quit dirvish_ in .vimrc

This was changed here
https://github.com/justinmk/vim-dirvish/commit/cfc66aa4486c911f4e6f802e0636c94d013952c7

Now I can manage it only by reverting the commit, which is a troublesome and unpreferred way. Thank you!

**Comment by justinmk** [comment]
`:help dirvish-options` : 

> |FileType| fires after Dirvish has loaded: all mappings, options, and content can be overridden by handling that event

```
    augroup dirvish_config
      autocmd!
      autocmd FileType dirvish nmap <buffer> <Plug>(dirvish_quit)
    augroup END
```
