### ISSUE TITLE
Refresh after mkdir

### ISSUE THREAD

**Issue by nomasprime** [justinmk/vim-dirvish#159]
After I run `!mkdir %…` I use `-` then `CR` to refresh Dirvish's directory listing.

Is this intended behaviour and if it is, is there a way to make the refresh automatic?

**Comment by justinmk** [comment]
I agree this should be automatic. 

> I use `-` then `CR` to refresh Dirvish's directory listing.

 You can use `R` or `:e` instead :)

**Comment by nomasprime** [comment]
Thanks @justinmk. `R` save a keystroke.

I'm trying to learn VimScript so I'll have a go at the automation. Any pointers?

**Comment by justinmk** [comment]
It should already work since
https://github.com/justinmk/vim-dirvish/commit/a74568d67144575152ce9cc797df131427b3d739

**Comment by nomasprime** [comment]
It's does. Thanks @justinmk 

![Party](https://media.giphy.com/media/10hO3rDNqqg2Xe/giphy.gif)
