### ISSUE TITLE
Override Sexplore/Vexplore

### ISSUE THREAD

**Issue by rgrinberg** [justinmk/vim-dirvish#16]
Anyway to make these open dirvish instead of netrw?

**Comment by mhinz** [comment]
You'd have to overwrite them:

```vim
command! -nargs=? -complete=file Vexplore leftabove vsplit | Dirvish <args>
command! -nargs=? -complete=file Sexplore belowright split | Dirvish <args>
```

Something like this.

By the way, if you don't want netrw to be run in the first place, use `let g:loaded_netrwPlugin = 1`.

**Comment by rgrinberg** [comment]
What about `:let g:loaded_netrw       = 1`? I just checked the docs and it mentions that i need to set that as well.

Thanks @mhinz i'll give that a try.

**Comment by justinmk** [comment]
Unfortunately netrw is still needed for `gx` (final nail in the coffin is to enhance https://github.com/justinmk/vim-gtfo to provide a `gx` alternative).

**Comment by rgrinberg** [comment]
Rats :/ I'll take working sexplore/vexplore over `gx` though

**Comment by mhinz** [comment]
@rgrinberg I quickly checked the sources and it looks as if `g:loaded_netrw` is used for `runtime/autoload/netrw.vim` whereas `g:loaded_netrwPlugin` is used for `runtime/plugin/netrwPlugin.vim` instead. So only setting the latter should be good enough.

@justinmk Oh, I see.

Not really sexy, but:

```vim
let g:loaded_netrw = 1
command! -nargs=? -complete=dir Vexplore leftabove vsplit | silent Dirvish <args>
command! -nargs=? -complete=dir Sexplore belowright split | silent Dirvish <args>
nnoremap gx :call netrw#BrowseX(expand((exists("g:netrw_gx")? g:netrw_gx : '<cfile>')),netrw#CheckIfRemote())<cr>
```
:-P

**Comment by tstelzer** [comment]
To offer a simple alternative mapping I use alot:
```
nmap  _ <C-w>v-
nmap <A--> <C-w>s-
```

**Comment by cometsong** [comment]
In combination (of @tstelzer and @mhinz), I use a function and a mapping, instead of going back to Vex'ing:
```
let g:loaded_netrwPlugin = 1
command! VleftDirvish leftabove vsplit | vertical resize 50 | silent Dirvish
nnoremap - :VleftDirvish<CR>
nnoremap gx :call netrw#BrowseX(expand((exists("g:netrw_gx")? g:netrw_gx : '<cfile>')),netrw#CheckIfRemote())<cr>
```
The `resize 50` is the dir's window width, which of course can be modified to whatever floats your boat.  ;)

**Comment by justinmk** [comment]
I think this would be too intrusive. Added a FAQ with sample code that can be pasted.
