### ISSUE TITLE
error: vim-fugitive deprecated fugitive#detect

### ISSUE THREAD

**Issue by bronzehedwick** [justinmk/vim-dirvish#166]
vim-fugitive has deprecated `fugitive#detect`, and now throws errors when they are used: https://github.com/tpope/vim-fugitive/commit/cd7db1d57cc991b27d9c9ce6552faea3075ada61

This is throwing these errors when activating dirvish.

```
Error detected while processing function fugitive#detect:
line 1:
E605: Exception not caught: Third party code is using fugitive#detect() which has been removed. Contact the author if you have a reason to still use it
E605: Exception not caught: Third party code is using fugitive#detect() which has been removed. Contact the author if you have a reason to still use it
```

![Screen Shot 2020-01-31 at 10 52 19 AM](https://user-images.githubusercontent.com/637174/73558298-e16ed200-4420-11ea-8f65-6862de9d6d84.png)

**Comment by fturcheti** [comment]
I was facing the same issue but it seems that it has been fixed in #161. So I discovered that the problem was in my .vimrc, where I had the following line:

```viml
autocmd FileType dirvish call fugitive#detect(@%)
```

Removing it fixed the problem.

**Comment by bronzehedwick** [comment]
Ah, you're right, thanks @fturcheti . I don't actually remember what that was used for, so I'll just keep it removed for now.

**Comment by fturcheti** [comment]
> I don't actually remember what that was used for, so I'll just keep it removed for now.

It was necessary to allow the usage of fugitive from a dirvish buffer. But I just discovered that dirvish brings this command built in [since 2017](https://github.com/justinmk/vim-dirvish/commit/decd833f9959670200e1fe2584ecec61dbe0d4a0#diff-b34a7d1b56f1d56d5487cf43f2a1f582).
