### ISSUE TITLE
Remapping the "-" key

### ISSUE THREAD

**Issue by pkrumins** [justinmk/vim-dirvish#171]
Hi Justin,

Thanks for creating this lightweight plugin! I really enjoy using it.

I am wondering what is the proper way to remap the `-` key to another key. I used the regular approach and put the following `nnoremap` statement in my `.vimrc`:

```
nnoremap <leader>d <Plug>(dirvish_up)
```

But, unfortunately, when I press `\d` (`\` is my leader key), it flashes a message that it's calling `<Plug>(dirvish_up)` but nothing happens. I verified that the mapping was created by running `:nnoremap \d` and vim said it was there. I further verified that the old mapping `-` no longer worked.

I then looked at dirvish.vim plugin itself and found that it was simply doing an `nmap`. I then tried it and got it working with the following statement:

```
nmap <leader>d <Plug>(dirvish_up)
```

The question that I have is, why didn't `nnoremap` work but `nmap` did and what is the proper way to remap the "-" key?

Thanks!

Peter

**Comment by lacygoill** [comment]
> why didn't nnoremap work but nmap did

The `nore` in `nnoremap` means "**no**n-**re**cursive".  Vim only expands the mapping once.  That is, `<leader>d` is replaced by `<Plug>(dirvish_up)` and that's it; but `<Plug>(dirvish_up)` doesn't mean anything, so Vim doesn't do anything.

> what is the proper way to remap the "-" key?

Use `nmap` so that the mapping is expanded twice:

    <leader>d
    →
    <Plug>(dirvish_up)
    →
    :<C-U>exe 'Dirvish %:p'.repeat(':h',v:count1)<CR>

**Comment by pkrumins** [comment]
Thanks for the info @lacygoill. Now I understand this!
