### ISSUE TITLE
`dirvish_up` doesn't seem to remember cursor position

### ISSUE THREAD

**Issue by tammersaleh** [justinmk/vim-dirvish#179]
when I...

1. open dirvish
2. descend into subdirectories
3. type `-` (mapped to `dirvish_up`) to go back up the stack
4. the cursor isn't positioned on the name of the directory I was previously in

I'm not sure if this is a feature request or a bug.  If it's a bug, I'll take a closer look at my vim config to ensure I'm not messing up the expected behavior.

**Comment by justinmk** [comment]
it definitely works for me. try without other plugins installed, or provide steps to reproduce with only dirvish installed

**Comment by tammersaleh** [comment]
Sorry about that – I'm pretty sure I figured out this was due to a mapping I had in place. Absolutely close this out.￼
