### ISSUE TITLE
Add additional spaces between icon and folder/file

### ISSUE THREAD

**Issue by PratikBhusal** [justinmk/vim-dirvish#181]
The main reason for something like this is to be able to use devicons within vim-dirvish. Currently, the filetype icons overlap with the file/folder name and it does not look that great. Below is a screenshot of the vim-dirvish repo:

![Image](https://i.imgur.com/JoADD6C.png)

The most noticeable example is with the `README.md` file where the right side of the arrow is cut off. Is there any way to add some spacing to make it look like it should?

**Comment by justinmk** [comment]
not possible yet, see https://github.com/justinmk/vim-dirvish/issues/145#issuecomment-524314280
