### ISSUE TITLE
Dirvish gets confused inside folders containing "$"

### ISSUE THREAD

**Issue by wincent** [justinmk/vim-dirvish#182]
#### To reproduce

```
mkdir 'x$y'
touch 'x$y/z'
vim 'x$y/z'
```

Then hit `-` to bring up Dirvish.

#### Expected result

- See Dirvish listing containing file, "z".

#### Actual result

- See empty dirvish listing.
- Bufname is `x$y/`.

If you hit `-` again, you will see the directory that contains the problem folder, and `x$y/` is present in the list.

#### Observations

Problem is that [the `glob()` call here](https://github.com/justinmk/vim-dirvish/blob/a19760770b810050e748de14ced589dd34c2dcb5/autoload/dirvish.vim#L46) is returning an empty list.

- `glob('/private/var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/tmp.5UImj1z0/x$y/*', 1, 1)` produces an empty list.
-  `glob('/private/var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/tmp.5UImj1z0/x$y/*', 0, 1)` produces an empty list also (ie. behavior is independent of suffix argument, and in any case, my `'wildignore'` is `*.o,*.rej`).
- `glob('/private/var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/tmp.5UImj1z0/x\$y/*', 1, 1)` **produces a non-empty list**.

ie. If I backslash-escape the `$` then everything works fine. In other words, an `fnameescape()` would fix this, but that might also escape too much. 🤷‍♂️

I'm testing this locally, but like I said, it may be too aggressive:

```diff
diff --git a/autoload/dirvish.vim b/autoload/dirvish.vim
index 4fd26a2..9c65b26 100644
--- a/autoload/dirvish.vim
+++ b/autoload/dirvish.vim
@@ -53,7 +53,7 @@ endif

 function! s:list_dir(dir) abort
   " Escape for glob().
-  let dir_esc = escape(substitute(a:dir,'\[','[[]','g'),'{}')
+  let dir_esc = fnameescape(escape(substitute(a:dir,'\[','[[]','g'),'{}'))
   let paths = s:globlist(dir_esc.'*')
   "Append dot-prefixed files. glob() cannot do both in 1 pass.
   let paths = paths + s:globlist(dir_esc.'.[^.]*')
```

**Comment by justinmk** [comment]
Thanks for debugging this! Does this patch work instead?

```diff
diff --git a/autoload/dirvish.vim b/autoload/dirvish.vim
index 4fd26a2..9c65b26 100644
--- a/autoload/dirvish.vim
+++ b/autoload/dirvish.vim
@@ -53,7 +53,7 @@ endif

 function! s:list_dir(dir) abort
   " Escape for glob().
-  let dir_esc = escape(substitute(a:dir,'\[','[[]','g'),'{}')
+  let dir_esc = escape(substitute(a:dir,'\[','[[]','g'),'{}$')
   let paths = s:globlist(dir_esc.'*')
   "Append dot-prefixed files. glob() cannot do both in 1 pass.
   let paths = paths + s:globlist(dir_esc.'.[^.]*')

**Comment by wincent** [comment]
Yep, that works @justinmk. Both for the synthetic test case that I listed in the summary and the real-world scenario where I originally ran into this.
