### ISSUE TITLE
:Shdo! doesn't insert full path of filenames if you traverse on subfolders

### ISSUE THREAD

**Issue by thisguychris** [justinmk/vim-dirvish#188]
## Description
If the files in the argslist are on a subfolder, and you do a `:Shdo!` in the project root, it doesn't insert the full path of the files in the arglist like `/projectroot/file`. But rather just file names `file`.

Eg. tree: `/projectdir`
.
├── bar
│   └── bar1.c
└── foo1.c

1 directory, 2 files

### Reproducible steps
1. vim
2. press `-` or `:Dirvish`
3. go to `bar` folder
4. press `x` on `bar1.c`
5. go up the directory, now on root (via `-`)
6. `:Shdo! mv {} %`

### Actual Behavior
Opens a shell script with:
> `mv 'bar1.c' /projectdir/`

### Expected Behavior
`bar1.c` should be full path

> `mv '/projectdir/bar/bar1.c' /projectdir/`

---
### Another example use-case:
1. ':args \`rg foo -l\`'
2. `:Shdo! mv {} %`

## Additional Note:
Surprisingly, the bug only shows if all the files are in the same subfolder. It doesn't show if the `arglists` have varied locations. So maybe there's an opportunity to beef up the logic there?

**Comment by justinmk** [comment]
confirmed. wonder how I missed that.

**Comment by jojoyuji** [comment]
Looking forward for this fix! 
Great work BTW, ditched NerdTree for vim-dirvish, and I'm loving it! tysm!
