### ISSUE TITLE
pattern delimiter not found

### ISSUE THREAD

**Issue by habamax** [justinmk/vim-dirvish#192]
With the recent update I get error opening dirvish:

![image](https://user-images.githubusercontent.com/234774/91812796-5f56be00-ec3a-11ea-8286-e654eb50da2b.png)

OS: Win10
vim: 8.2.1558
nvim: current nightly

**Comment by justinmk** [comment]
cc @lxhillwind

**Comment by habamax** [comment]
with 

* `vim -u NONE`
* `set nocp`
* `set conceallevel=2`
* `packadd vim-dirvish`
* `-`

I don't get errors but also no syntax and no conceal:

![image](https://user-images.githubusercontent.com/234774/91814152-61ba1780-ec3c-11ea-8b7c-db6373c7f871.png)

**Comment by habamax** [comment]
Okay, you have to escape `\` in `[^\\]` as was in previous version

**Comment by habamax** [comment]
```
" Define once (per buffer).
if !exists('b:current_syntax')
  exe 'syntax match DirvishPathHead =.*'.s:sep_esc.'\ze[^'.s:sep_esc.']\+'.s:sep_esc.'\?$= conceal'
  exe 'syntax match DirvishPathTail =[^'.s:sep_esc.']\+'.s:sep_esc.'$='
  exe 'syntax match DirvishSuffix   =[^'.s:sep_esc.']*\%('.join(map(split(&suffixes, ','), s:escape), '\|') . '\)$='
endif
```
This works for me

**Comment by habamax** [comment]
And having this makes `s:sep` redundunt, probably better just escape and use it like so:

```
let s:sep = escape(exists('+shellslash') && !&shellslash ? '\' : '/', '\\')
let s:escape = 'substitute(escape(v:val, ".$~"), "*", ".*", "g")'

" Define once (per buffer).
if !exists('b:current_syntax')
  exe 'syntax match DirvishPathHead =.*'.s:sep.'\ze[^'.s:sep.']\+'.s:sep.'\?$= conceal'
  exe 'syntax match DirvishPathTail =[^'.s:sep.']\+'.s:sep.'$='
  exe 'syntax match DirvishSuffix   =[^'.s:sep.']*\%('.join(map(split(&suffixes, ','), s:escape), '\|') . '\)$='
endif
```
