### ISSUE TITLE
Tex icon affects filename

### ISSUE THREAD

**Issue by mrossinek** [justinmk/vim-dirvish#204]
I was unsure whether to file this issue here or at https://github.com/kyazdani42/nvim-web-devicons so I am going to tag @kyazdani42

Today I noticed the following bug:
![screenshot_1605115011](https://user-images.githubusercontent.com/21973473/98843459-4db84080-244b-11eb-8c04-00729e540762.png)
On the left you can see a dirvish buffer of the contents as listed on the right.

On line 6 you can see that the filename of the tex file is printed in reverse! I have no idea what could cause this but without the devicons it obviously does not happend. 

I use [this](https://github.com/mrossinek/dotfiles/blob/master/nvim/.config/nvim/after/plugin/vim-dirvish.vim) to display the icons:
```vim
call dirvish#add_icon_fn({p -> luaeval("require('nvim-web-devicons').get_icon(vim.fn.fnamemodify('" .. p .. "', ':e')) or ' '")})
```

**Comment by kyazdani42** [comment]
well i don't think this should be related to icons. Could you reproduce with a super minimal vimrc ? like only dirvish and web devicons ?

**Comment by mrossinek** [comment]
On my system, starting `nvim -u NONE` and then sourcing the following file, seems to do the trick at reproducing the issue:
```vim
packadd vim-dirvish
packadd nvim-web-devicons
call dirvish#add_icon_fn({p -> luaeval("require('nvim-web-devicons').get_icon(vim.fn.fnamemodify('" .. p .. "', ':e')) or ' '")})
```

**Comment by kyazdani42** [comment]
I don't think this issue can come from nvim-web-devicons, which only returns an icon and a highlight group. It doesn't operator on text. Dirvish must do something weird with the result.

**Comment by kyazdani42** [comment]
`:lua print(require'nvim-web-devicons'.get_icon('tex')..' test.tex')` doesn't produce any weird stuff. This issue is dirvish related imo.

**Comment by mrossinek** [comment]
> `:lua print(require'nvim-web-devicons'.get_icon('tex')..' test.tex')` doesn't produce any weird stuff. This issue is dirvish related imo.

Actually, I observe the same strange behavior when *not* placing the space between the icon and the text. I.e.:
```
lua print(require('nvim-web-devicons').get_icon('tex')..'test.tex')
```
Gives: `xet.tsetﭨ`

PS: Sorry for the long delay, I only just found time to look into this again.

**Comment by mrossinek** [comment]
Try for example opening the following file:
```
Text before TeX character:
test ﭨ

Text after TeX character (with a separating space):
ﭨ test

Text after TeX character (withOUT a separating space):
ﭨtest
```

Here is a screenshot of the results:
![screenshot_1607262855](https://user-images.githubusercontent.com/21973473/109042135-20c52c00-76d0-11eb-9ef7-98fe4f44cc51.png)

The editors are:
* Top left: `nvim test.tex`
* Bottom left: `nvim --noplugin --clean test.tex`
* Top right: `\vim test.tex`
* Bottom right: `\vim --noplugin --clean test.tex`

System: `Linux 5.10.16-arch1-1`
Neovim: `NVIM v0.5.0-dev+1094-gd623400ca`
Vim: `VIM - Vi IMproved 8.2; Included patches: 1-2489`

**Comment by mrossinek** [comment]
The issue does not appear in `alacritty` so I am starting to believe it lies with `kitty`. I will close this here and take my issue there..
