### ISSUE TITLE
Default color of files unreadable in dark mode

### ISSUE THREAD

**Issue by TamaMcGlinn** [justinmk/vim-dirvish#208]
It seems the default colours for me are a lightgray on a darkgrey background for regular files, using `background=dark`. is there any way to configure dirvish's colours?

**Comment by justinmk** [comment]
sounds like whatever colorscheme you are using is flawed. 

dirvish only links to vim's highlight groups, e.g. `:help hl-Directory`. dirvish does not decide colors at all. that is up to your colorscheme or personal config.

try this:

    :highlight Directory ctermfg=red guifg=red
