### ISSUE TITLE
Feature: Dot Repeatable Commands

### ISSUE THREAD

**Issue by srafi1** [justinmk/vim-dirvish#209]
Currently, hitting period (.) sets you up to run a command. It would be nice to have a way of repeating that command for other files similarly to how you can repeat actions by hitting period in normal mode when editing text. This would require using a different key, of course, but AFAIK it is not currently implemented.

An example of how this would work:
Hit `-` to go the the parent directory with contents:
```
file1
file2
```

Hit `.` with the cursor on `file1` and type `du -h` to get the following command:
```
!du -h 'file1`
```

After running the command, move the cursor down to `file2` and hit the repeat key to get the following command:
```
!du -h 'file2'
```

**Comment by justinmk** [comment]
This would require some sort of template syntax, e.g.

    !du -h {}

then you're in programming territory, so it doesn't gain much over using a macro or a throwaway mapping, or simply `@:`.

In your example, just do this:

    :exe '!du -h '.shellescape(getline('.'))

then repeat it via `@:` .
