### ISSUE TITLE
Overriding default mappings

### ISSUE THREAD

**Issue by jonathf** [justinmk/vim-dirvish#21]
Hey, vim-dirvish team!

I've been looking for a no-frills directory viewer like this. It is quite awesome.

I would like to set up my own custom mappings inside of dirvish. For this I needed to free up/move the keybindings for '/', '?' and '<cr>' etc..

Would it be possible to add an option such that user easily can change the various keybinding? Perhaps hard-bind them to `<plug>(dirvish-...)` and optionally map default keys to those?

**Comment by nhooyr** [comment]
Can't you just use a autocmd?

**Comment by AssailantLF** [comment]
I believe this feature has been added, if it wasn't when you made your post.

See `:help dirvish-options`, and then scroll down a bit. You have to use autocommands to set your remaps when the dirvish filetype is detected.

Maybe not the best approach, but I have a few things remapped in this way with no problems.

**Comment by justinmk** [comment]
I kept this issue open because I'm still trying to decide if adding `<Plug>(dirvish_foo)` mappings makes sense.

**Comment by jonathf** [comment]
Indeed, it seems that `autocmd` plus `map<buffer>` works well.

**Comment by idbrii** [comment]
> trying to decide if adding <Plug>(dirvish_foo) mappings makes sense.

The i a o / ? mappings are nontrivial, so plugs would make sense. I'd assume the reason to avoid is to keep it simpler and to better define what dirvish does.

One of the highlights of dirvish used to be that you could slice and dice the buffer, but I no longer see that in the readme. Overriding basic insertion communicates that reorganizing files is cool, but modifing them is better done in a scratch buffer.

I've banged up against this a couple times and I've accepted this philosophy. I think I'll try to make a command to send visible contents to a scratch buffer...

**Comment by justinmk** [comment]
@idbrii I'll add `<Plug>` maps.

> One of the highlights of dirvish used to be that you could slice and dice the buffer, but I no longer see that in the readme. 

That blurb lives in the [help doc](https://github.com/justinmk/vim-dirvish/blob/master/doc/dirvish.txt#L25) (removed from the README in some attempt to de-noise/de-duplicate). It's still very much a supported use-case.

> Overriding basic insertion communicates that reorganizing files is cool, but modifing them is better done in a scratch buffer.

 `i`/`a`/`o` were  chosen because they cover the smallest surface area of actions that a user is likely to want to do (without resorting to leader maps). In fact `'modifiable'` is [set](https://github.com/justinmk/vim-dirvish/commit/80e9bab2fc230ace304b23225c74e4010ea3f319) unlike pretty much every other directory browser plugin, to further emphasize the malleability of the buffer. Though `:global`, `:sort`, etc make sense to me I would think wanting to insert text would be most uncommon.

**Comment by onemanstartup** [comment]
@justinmk Doesn't it make sense to add this mapping by default?
```vim
autocmd FileType dirvish nnoremap <silent><buffer> l :<C-U>.call dirvish#open("edit", 0)<CR>
autocmd FileType dirvish nnoremap <silent><buffer> h :<C-U>exe "Dirvish %:h".repeat(":h",v:count1)<CR>
```

**Comment by idbrii** [comment]
@onemanstartup How would you move left/right in a filename? (Try `$` if l/h seem to do nothing for you.)

**Comment by plexigras** [comment]
i dont understand how do i for example remap `.` to `,` so my normal `.something` keybindings work?

**Comment by justinmk** [comment]
Using a `FileType dirvish` handler to override mappings, should be 100% reliable after https://github.com/justinmk/vim-dirvish/commit/197afdfdf1d837cbebf31f699bdefe2cff64073a .

**Comment by idbrii** [comment]
@justinmk While `FileType dirvish` allows users to supply additional mappings and remove existing mappings (and it works great!), it does not allow them to change existing mappings.

I want to map `<C-L>` to refresh, so I have to map it to `R` and thus I cannot unmap `R` (or I must copypaste code from inside dirvish).

It [works for me](https://github.com/idbrii/daveconfig/blob/92e806f6c50131748ccef71a3bcab7cf06f7bf6f/multi/vim/ftplugin/dirvish.vim#L25-L27) but it could be friendlier.

**Comment by justinmk** [comment]
@idbrii Thanks for the feedback. No opposition to more `<Plug>` mappings, though it's low priority.
