### ISSUE TITLE
Weird behavior when directory is opened with vim.cmd (Neovim's Lua API)

### ISSUE THREAD

**Issue by gbrlsnchs** [justinmk/vim-dirvish#215]
I'm using a nightly release of Neovim.

Steps to reproduce:
1. Open any text buffer
2. Execute `lua vim.cmd("vsplit +edit ./a/directory/path")`

Expected:
It should open the buffer normally, displaying the directory's content, just like it does when running `:vsplit +edit ./a/directory/path` directly.

Actual result:
It opens the buffer, but doesn't display its contents. If you hit <kbd>R</kbd> or move out the window and in again, then it shows the directory's content.

**Comment by justinmk** [comment]
Looks like a `nvim_exec` doesn't execute autocmds...

**Comment by justinmk** [comment]
seems to work now (tested nvim ca64b589cd74 ), can you confirm?
