### ISSUE TITLE
vim-sneak highlighting persists across dirvish buffers

### ISSUE THREAD

**Issue by chiphogg** [justinmk/vim-dirvish#22]
[vim-sneak](https://github.com/justinmk/vim-sneak) is indispensable for long directory listings.  Type two characters, and I'm right at the directory I'm trying to get to, so just hit `<Enter>` and go!

Unfortunately, the sneak highlighting carries over to this new buffer.  Moving around doesn't kill it, either; I have to hit `<Esc>`.

This seems very reproducible:

1. Make a directory where two entries have a common substring, *and* the first entry is a directory which contains a file with that same substring.  e.g.,

  ```
  testdir/dir_xx/file_xx
  testdir/file_xx
  ```

  (The second entry `testdir/file_xx` is needed to trigger sneak highlighting, which won't happen if there's just one entry.)

2. Open `testdir` in dirvish.
2. Sneak to `xx` (make sure that `dir_xx` is the first entry sneak finds).
3. Hit `<Enter>` to go into `dir_xx`
5. Observe that the `xx` in `file_xx` is still sneak-highlighted, when it shouldn't be.

I am not sure if this is a bug for dirvish or sneak.  Maybe you can get together with the author of sneak and figure out where the problem lies.

**Comment by justinmk** [comment]
Thanks for the report. I repro'd it once and now can't anymore, for some reason. Might have something to do with the use of `:noau` in the plugin, which may be de-emphasized at some point.

**Comment by justinmk** [comment]
@chiphogg If you remove `noau` from [this line](https://github.com/justinmk/vim-dirvish/blob/80e9bab2fc230ace304b23225c74e4010ea3f319/autoload/dirvish.vim#L236) and re-source the file (or restart vim) are you able to reproduce?

**Comment by chiphogg** [comment]
This is weird, but I can't repro either on my personal laptop.  It is annoyingly consistent on my work computer.  I will try again later this week when I get back to work.

**Comment by justinmk** [comment]
@chiphogg What is `:version` in each case?

Probably sneak.vim just needs to make its temporary listener global--there's no reason for it to be buffer-local.

**Comment by chiphogg** [comment]
Do you want the full `:version` output in each case?

My home computer is `7.4.882`.  I think my work computer is `7.4.899`.

**Comment by justinmk** [comment]
Just the versions are enough, thanks.

**Comment by chiphogg** [comment]
I am able to reproduce after I remove `noau` from that line.

**Comment by justinmk** [comment]
@chiphogg This should be fixed with the latest version of sneak.vim:

https://github.com/justinmk/vim-sneak/commit/5da6de3b5bf28681124eb3e10a308313a58dd5b8

**Comment by chiphogg** [comment]
Wonderful!  The problem has vanished.  Thank you!
