### ISSUE TITLE
[Feature request] Add config for map /

### ISSUE THREAD

**Issue by jqhr** [justinmk/vim-dirvish#222]
I like dirvish. but sometimes it confused me for mapping /.
I have an other plugin called 'wilder.nvim', it could support fuzzy find for search pattern. but dirvish remap /. so I cannot use fuzzy find in dirvish.

**Comment by justinmk** [comment]
No need for a new option. All dirvish buffer settings can easily be overridden by using a FileType autocmd.

    autocmd FileType dirvish unmap <buffer> /

see `:help dirvish-options`.
