### ISSUE TITLE
Problem remap Explore

### ISSUE THREAD

**Issue by thevan96** [justinmk/vim-dirvish#224]
I remap dirvish like netrw: Explore, Vexplore.
But using it with no arguments does not show the file's directory we are editing, instead of the folder root.

How to remap Explore, Vexplore when using it with no arguments will show the directory of the file we are editing?

**Comment by justinmk** [comment]
say exactly what you tried, in code

**Comment by thevan96** [comment]
```
let g:loaded_netrwPlugin = 1
command! -nargs=? -complete=dir Explore Dirvish <args>
command! -nargs=? -complete=dir Sexplore belowright split | silent Dirvish <args>
command! -nargs=? -complete=dir Vexplore leftabove vsplit | silent Dirvish <args>
``` 
I want to explore the folder where the current file is.

**Comment by justinmk** [comment]
command! -nargs=? -complete=dir Explore exe 'Dirvish '.(empty(<q-args>)?'%':<q-args>)
