### ISSUE TITLE
Delete buffer

### ISSUE THREAD

**Issue by thevan96** [justinmk/vim-dirvish#225]
How to auto-delete buffer if the file is removed from the disk?

![Peek 2022-06-17 09-40](https://user-images.githubusercontent.com/47932916/174214141-56beca47-e1c4-4123-979c-9b9f69e3c1a1.gif)

**Comment by justinmk** [comment]
can use a `ShellCmdPost` handler, e.g.

    autocmd ShellCmdPost * exe 'bdelete' expand('<afile>')

but that won't cover all cases. Vim doesn't have inotify events afaik. You could use something like https://github.com/clibs/entr
