### ISSUE TITLE
dir up stopped working

### ISSUE THREAD

**Issue by TamaMcGlinn** [justinmk/vim-dirvish#226]
I was used to being able to press `-` to go up from one directory to its parent. This commit broke that:

```
├ 2022-07-13 [6f52d72] {Justin M. Keyes} fix: <Plug>(dirvish_up) fails on crazy filenames
```

I'm still investigating why.

**Comment by TamaMcGlinn** [comment]
Found it; looks like you removed this default mapping accidentally:

```
if !hasmapto('<Plug>(dirvish_up)', 'n')
  execute 'nmap '.s:nowait.'<buffer> - <Plug>(dirvish_up)'
endif
```

**Comment by justinmk** [comment]
It wasn't an accident, there is already a global mapping defined in `plugin/dirvish.vim`. Did you override the global `-` mapping? If so, you can define a buffer-local one:

    au FileType dirvish nmap ? <plug>(dirvish_up)

**Comment by TamaMcGlinn** [comment]
Just a typical case of [spacebar heating](https://xkcd.com/1172/) :) I am adjusting the workaround in my plugin, no need for any changes in dirvish. In case you're interested in the details:

I use terminals inside NeoVim a lot, and sometimes I change directories in that terminal, but then find I want to quickly open up one of the directories mentioned on the commandline. Since just remapping inside ftplugin/terminal.vim doesn't work (vim-dirvish mapping takes preference over it), my chosen hack was to remap globally and check the filetype inside the function:

```
function! browsedir#BrowseDir() abort
  if &buftype ==# 'terminal'
    let l:dir = dirhere#GetDirFromPrompt()
    call better_gf#JumpToNormalBuffer()
    execute ':e '.l:dir
  else
    e %:h
  endif
endfunction
```

Since I also wanted to support people using non-Dirvish editors, I call `e %:h` which ends up calling Dirvish. This happened to work because Dirvish was also mapping the key again in the ftplugin file.

I was, of course, not aware of any of this interplay until your recent commit, which rightly calls the ftplugin mapping superfluous.
