### ISSUE TITLE
respect b:did_ftplugin

### ISSUE THREAD

**Issue by haolian9** [justinmk/vim-dirvish#229]
i tried to disable dirvish's default `ftplugin/dirvish.vim` by adding `let b:did_ftplugin = 1` to `stdpath('config')/ftplugin/dirvish.vim`, but it does not work as expected.

**Comment by justinmk** [comment]
I can add support for `b:did_ftplugin`. 

TODO: from `:help ftplugin` : 

```
If you are writing a filetype plugin to be used by many people, they need a
chance to disable loading it.  Put this at the top of the plugin: >

	" Only do this when not done yet for this buffer
	if exists("b:did_ftplugin")
	  finish
	endif
	let b:did_ftplugin = 1

This also needs to be used to avoid that the same plugin is executed twice for
the same buffer (happens when using an ":edit" command without arguments).

Now users can disable loading the default plugin completely by making a
filetype plugin with only this line: >

	let b:did_ftplugin = 1

**Comment by haolian9** [comment]
oh, i was talking to this [line](https://github.com/justinmk/vim-dirvish/blob/81b40878f286f370df2a2b3a52c4d860643d2142/autoload/dirvish.vim#L498)

**Comment by haolian9** [comment]
> I can add support for b:did_ftplugin.

yeah, that's the behavior i am looking for.

**Comment by haolian9** [comment]
i finallly realized how easy can this be fixed :)
would you mind to have a look at this pr? @justinmk

**Comment by haolian9** [comment]
after dug deeper, i dont think this is a bug. although this hardcode `source` existed since #105, i disabled this source in my fork and used for a couple week, i did not encounter any problems with my keymaps.
i respect this setting and going to close this issue.
