### ISSUE TITLE
i do have a need to set `&buftype=wipe` for a dirvish buf

### ISSUE THREAD

**Issue by haolian9** [justinmk/vim-dirvish#230]
i am trying to open dirvish in a floatwin, so i have to create buffer for dirvish. and i'd like to set the buffer's `&buftype` to wipe to prevent buffer leaking.
i know there is a vimscript approach somewhere  in an issue, but i want to re-implement it via lua, so that i can maintaince it myself.
so, do you think it's worth to relax the `&buftype!=wipe`constraint or make it optional?

**Comment by haolian9** [comment]
i just found a lua port of this plugin, as i'm more familiar to lua, i decided to find some luck in there.

sorry for the noise, many thanks for making this awesome plugin!

**Comment by justinmk** [comment]
> and i'd like to set the buffer's `&buftype` to wipe to prevent buffer leaking.

"Leaking" how? It's an unlisted buffer. Won't appear in `:ls`, only `:ls!`.

**Comment by haolian9** [comment]
i could be wrong for using "leaking" term here, i thought every buffer created for dirvish should be :bwipe, actually i see no reason to keep that buffer for it to reuse again.
and in my observe, the following operation flow will not create a unlisted buffer.
```
$ nvim
" in nvim now
:Dirvish
" selected a file
<cr>
```

**Comment by haolian9** [comment]
wait, since the unlisted buffer has been initialized by dirvish which means it has proper syntax highlight and ftplugin behavior, in this perspective it's worth to be reused. 
then why dose not dirvish keep this buffer in the previous operation flow?

**Comment by justinmk** [comment]
> i thought every buffer created for dirvish should be :bwipe, actually i see no reason to keep that buffer for it to reuse again.

There are definitely reasons. If the buffers are wiped, jumps won't work well, cursor position will be lost, `b:` state is lost, highlighting, etc. That state needs to be stored somewhere. Buffers are _designed_ to be used in this way. Eradicating them and storing the state somewhere else, makes no sense.

>  in my observe, the following operation flow will not create a unlisted buffer.

Vim is extremely tricky with buffers. That single Dirvish buffer is listed (so what?), but if you visit many Dirvish buffers with `-`, you'll see that most of them are unlisted. 

> then why dose not dirvish keep this buffer in the previous operation flow?

Not sure what you mean.

**Comment by haolian9** [comment]
thanks for the detailed explanation!
after i scratched my own impl, i truly understood the first part of your reply. especially for why dirvish keeps a buffer for each visited dir.

back to my original demand, it turns out i dont need to create new buffer for
invoking dirvish, and i finally got a working in process snippet, but it's getting off-topic to this issue.

i'm sorry this issue has took you so long.

```
local api = vim.api

local function fly()
  -- instead of keep creating new buf for dirvish, just use the current buf
  -- local bufnr = api.nvim_create_buf(false, true)
  local bufnr = api.nvim_get_current_buf()

  local cwd = vim.fn.expand("%:p:h")
  local win_id = api.nvim_open_win(bufnr, true, {
    relative = "editor",
    width = 30,
    height = 20,
    row = 3,
    col = 2,
    style = "minimal",
  })
  api.nvim_command(string.format("Dirvish %s", cwd or ""))

  api.nvim_create_autocmd("WinLeave", {
    callback = function()
      api.nvim_win_close(win_id, true)
      return true
    end,
  })

  -- todo: when user chose one file, close dirvish winow, then open the chosen
  -- file in the original window or in a new split window
  -- if there is a custom event there would be a easier way to achieve this goal
end

fly()
```
