### ISSUE TITLE
Examples for copy, move, delete, rename, create commands

### ISSUE THREAD

**Issue by alextes** [justinmk/vim-dirvish#231]
After using I think literally every file manager plugin available, dirvish still has the best core for me (buffer based), but it comes with almost no default configuration. Several interactions are critical for me with a file manager. I guess dirvish is more a browser, and expects you to bring the manager. I almost never use one (prefer fzf) but when I do, it's to create, move, rename, or destroy files and folders. The usual!

Although the dirvish help is helpful, it doesn't provide ready-made commands that can be mapped to a key. This issue is both for me to get help figuring these out, and crowdsource existing solutions. Perhaps maintainers would even be interested in either providing these as examples in the help, expanding the help to make these cases easier for others to find, adding them as commands, or even adding them as defaults if many people like them, but from searching the issues I don't think it's likely 😅 .

[vim-dirvish-dovish](https://github.com/roginfarrer/vim-dirvish-dovish) has a bunch of things I think make great defaults but a couple that are more surprising like how it renames only single files, or doesn't move from the arglist. So I'll steal the pieces that fit right into dirvish and leave the ones that fit less well. Perhaps the final result can go into that plugin or a new plugin.

I'll be listing critical pieces I need, I'll fill them in over time but if you already have one or want to provide one _please do!_. I'm no vim expert but I guess the best would be for every entry to have its own command that people can copy and bind.

Must have:
* copy file/folder to provided path
* move file/folder to provided path
* delete file/folder
	* https://github.com/roginfarrer/vim-dirvish-dovish/blob/main/ftplugin/dirvish.vim#L104
* rename file/folder
	* https://github.com/roginfarrer/vim-dirvish-dovish/blob/main/ftplugin/dirvish.vim#L122
* create new file/folder
	* https://github.com/roginfarrer/vim-dirvish-dovish/blob/main/ftplugin/dirvish.vim#L63
	* https://github.com/roginfarrer/vim-dirvish-dovish/blob/main/ftplugin/dirvish.vim#L82 

Should have:
* copy arglist to current dir
* move arglist to current dir
* delete arglist (maybe yanked is less useful here)
* trash arglist file/folder (might be hard to do cross-OS)

Nice to have:
* copy file/folder under cursor to provided path
* move file/folder under cursor to provided path
* copy arglist to provided path
* move arglist to provided path
* rename multiple files
* copy yanked to current dir
* move yanked to current dir

Selecting what to act on is pretty well covered, yank and arglist work great. Applying copy, move, delete to them isn't covered, whether they should target the current directory or a path to be input, isn't either.

Renaming multiple is a beast of its own. I think the most natural would be for the command to accept input after triggering for a single file. For multiple Shdo seem much more ideal, populating a buffer that you can edit with the files pre-populated.

Thanks for the great dirvish plugin! 💛

**Comment by alextes** [comment]
Another helpful bit is to put all these bindings under an augroup like detailed in the help files:

```
augroup dirvish_config
  autocmd!

  autocmd FileType dirvish nnoremap <silent><buffer> m :!mv <c-r>" %<CR>

augroup END

**Comment by alextes** [comment]
I managed to do one, and that's all I have time for right now 😭 .

* move file / folder to provided path

```vimrc
function! g:DirvishDoMove() abort
  let target = trim(getline('.'))
  let filename = fnamemodify(target, ':t')
  let newname = input('Move to: ')
  let cmd = 'mv ' . shellescape(target) . ' ' . shellescape(expand("%") . newname . '/' . filename)
  let output = system(cmd)
  if v:shell_error
    call s:logError(output)
  endif

  " Reload the buffer
  Dirvish %
endfunction
```

Bound like so:
```vimrc
autocmd FileType dirvish nnoremap <silent><buffer> m :call DirvishDoMove()<CR>
```

**Comment by alextes** [comment]
Too much work for me, closing this for now.

**Comment by justinmk** [comment]
Thanks for looking into this. I'm open to adding some well-selected default behaviors, but ...

> Must have:
> 
> * copy file/folder to provided path
> * move file/folder to provided path
> * delete file/folder

"delete" is just so easy already (`.rm<cr>` or `.rm -rf<cr>Z!`), and making a destructive even easier is questionable. I'm also skeptical about copy/move. I tend to think people who want this just haven't tried the `.` + `Z!` workflow yet and/or aren't yet super familiar with shell operations. It doesn't take much...

> copy arglist to current dir
> move arglist to current dir

I agree these are awkward currently. 

> delete arglist

This is already easy: `[count].rm<c>Z!`

> copy file/folder under cursor to provided path

What interface is going to be better than the already-existing `:` interface? Prompts are prompts.

> Renaming multiple is a beast of its own. I think the most natural would be for the command to accept input after triggering for a single file

Yeah, this was one of the original motivations for Dirvish. Editing a script is easier, more intuitive, and (if Vim is doing its job...) faster, than learning a quasi-pseudo-DSL for another tool.



> Thanks for the great dirvish plugin! 💛

Thanks for the kind words!
