### ISSUE TITLE
`vidir` like functionality in dirvish

### ISSUE THREAD

**Issue by kovasap** [justinmk/vim-dirvish#238]
I just learned about a cool tool called [`vidir`](https://linux.die.net/man/1/vidir) that lets you rename files by editing their names in a vi buffer that looks very similar to a dirvish buffer.  It seems like it would be very natural to replicate this functionality in dirvish itself.  Has this ever been considered?

**Comment by justinmk** [comment]
Yes it was considered. The name "dirvish" is partially a reference to vidir and similar tools. Emacs [dired](https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html) has similar functionality.

But Dirvish intentionally doesn't try to add a magic layer. The goal is just to leverage Vim's shell + editing features. `:Shdo` and related mappings make it fairly ergonomic to "rename files by editing their names in a vi buffer", did you try that?
