### ISSUE TITLE
dirvish_up extremly slow

### ISSUE THREAD

**Issue by miguel9554** [justinmk/vim-dirvish#239]
In `vimrc` I've mapped `-` to dirvish_up

```vim
au FileType dirvish nmap - <plug>(dirvish_up)
```

Using it is extremely slow, taking around 1-5 seconds to run

**Comment by justinmk** [comment]
Maybe a recursion issue. What does `:nmap -` show ?

**Comment by miguel9554** [comment]
ok, this is reported

````
n  -             <Plug>(dirvish_up)
n  -w          * ':Rgf '.expand('<cword>').'<CR>'
Press ENTER or type command to continue
```

**Comment by miguel9554** [comment]
That was it, just unmapped the `-w` and now dirvish UP works instantly. THANKS!
