### ISSUE TITLE
don't add CWD (current working directory) to `args` when starting as `vim .`

### ISSUE THREAD

**Issue by brianhuster** [justinmk/vim-dirvish#248]
One thing that quite trouble me is that when I start Dirvish whith `nvim .` or `vim .`, it will automatically add the current directory to the `arglist`. So if I want to `Shdo!`, I must delete that directory from the arglist first. Is there a way to make it not automatically add that directory to arglist when I start up as `nvim .` or `vim .`?

**Comment by justinmk** [comment]
I'd be fine with special-casing CWD to avoid this by default.

**Comment by brianhuster** [comment]
Sorry, I'm not very good at English, what do you mean by "special-casing CWD"?

**Comment by brianhuster** [comment]
For now, I'm not sure if this is caused by the plugin or if it is a default behavior of Vim. 

I'm not very good at Vimscript btw, that's also the reason my PR [#247] only modify 2 lines.

**Comment by justinmk** [comment]
Er, this is a result of how args (the arglist, `:args`) work in Vim. Vim adds the args to the arglist. Would be surprising for Dirvish to remove from the args list. And then special-casing this also doesn't really make sense.

I guess `vim .` is intended to show the Dirvish buffer immediately. So Dirvish could detect when it's the first buffer, or during startup... this gets ugly though, and explaining it in documentation is noisy.

Why can't you just run `vim` and hit `-` if you don't want this behavior?

**Comment by brianhuster** [comment]
Thank you! Not so related here, but can you please check my PR #248
