### ISSUE TITLE
Opening a split doesn't focus it?

### ISSUE THREAD

**Issue by mtglsk** [justinmk/vim-dirvish#26]
Is this by design? Because netrw seems to focus the opened split.

**Comment by justinmk** [comment]
The default mappings keep the focus. `<c-w> f` built-in will do what you want, or a trivial map like

    nmap <buffer> A :vsplit<bar><CR>

**Comment by mtglsk** [comment]
Ok, thanks for explanation.

**Comment by justinmk** [comment]
@mtglsk The reasoning is: if you are splitting a file, most likely you plan to continue navigating to other files in the dirvish buffer. That's in addition to the fact Vim's default window split commands already behave in the other way as mentioned above.

Hope that makes sense, or let me know if I'm out of touch.
