### ISSUE TITLE
Relative directories doesn't always update?

### ISSUE THREAD

**Issue by nhooyr** [justinmk/vim-dirvish#29]
Very simple to reproduce. I'll just illustrate the idea below.

Start in your home directory.
1. `nvim ~/scratch`
2. select a random file, any file
3. `:lcd ~/scratch`
4. `:Dirvish`
5. Now if you try to select any file, it'll give you an error because it still thinks you are in your home directory for some reason.

**Comment by justinmk** [comment]
It's a feature--but I know it's often surprising so it probably needs to be changed. Currently, directories are never auto-reloaded.

**Comment by nhooyr** [comment]
Perhaps a simple autocmd that triggers whenever a Dirvish buffer is entered?

**Comment by justinmk** [comment]
This would address that:

    au BufEnter * if &ft ==# 'dirvish' ...

But, I still think probably it should reload by default, except for large directories (then show a brief message maybe)
