### ISSUE TITLE
:Shdo suggestion to make {} optional

### ISSUE THREAD

**Issue by edkolev** [justinmk/vim-dirvish#33]
Hi, and thank you for this plugin!

I would like to suggest the following change to `:Shdo`'s behaviour: make `{}` optional. If not supplied, `:Shdo` should behave as if ` {}` was supplied at the end.

For example, these would be identical:
- `:Shdo rm {}`
- `:Shdo rm`

This behaviour would be similar to `xargs`.

In case you don't think this change is appropriate, I think `:Shdo` should show an error if `{}` is not supplied.

Thanks!

**Comment by justinmk** [comment]
That's actually how I originally implemented it. I found it too confusing and too magic. The presence of the pre-filled `{}` is also a nice hint to help users understand the pattern. Without requiring {}, if one needs to do a rename (e.g. `:'<,'>Shdo mv {} {}2`), it's confusing: "do I need to add two instances of {}, or only one?".

Did you try the `x` mapping, which pre-fills the command line?

> This behaviour would be similar to xargs.

Hmm, good point. 

> I think :Shdo should show an error if {} is not supplied.

:+1: Agreed. 

Since it's a one-liner to implement as a command-mapping, I'd prefer to stick with the no-magic behavior.

    autocmd FileType dirvish cnoremap <buffer> <CR> <C-R>=(getcmdline()[-2:]=='{}'?'':'{}')<CR><CR>

**Comment by mhinz** [comment]
I changed the PR to document the "x" mapping instead. ;-)

**Comment by edkolev** [comment]
The "x" mapping seems useful, but I'm probably going to stick with the :Shdo command.

I've created a PR, let me know if it can be improved.

**Comment by justinmk** [comment]
I think maybe I've convinced myself that the original suggestion here is fine, but it should not be documented. The DWIM behavior is better than an error, but for the normal case, user should be thinking about explicitly specifying the placement of `{}`.

In other words: Trying to explain this feature makes the documentation more complicated, but it has to be handled either with an error or with DWIM, so choose DWIM.

**Comment by edkolev** [comment]
Makes sense.

I've updated the PR. I tried to minimise the number of new lines, which seems to be a goal for this plugin.

Again, let me know if anything should be improved.
Maybe ` {}` (with whitespace) should be appended if `cmd` is non-empty, but only `{}` (without whitespace) should be appended when `cmd` is empty.

**Comment by justinmk** [comment]
> Maybe {} (with whitespace) should be appended if cmd is non-empty, but only {} (without whitespace) should be appended when cmd is empty.

Sure.

**Comment by edkolev** [comment]
PR is now updated.

This change now spans across 2 lines. I could reduce the lines to 1, at the cost of readability:
```
let cmd = stridx(a:cmd, '{}') >= 0 ? a:cmd : empty(a:cmd) ? '{}' : a:cmd . ' {}'
```

For comparison, in the PR the assignment is:
```
let cmd = empty(a:cmd) ? '{}' : a:cmd
let cmd = stridx(cmd, '{}') == -1 ? cmd . ' {}' : cmd
```

Again, let me know if anything should be improved, or the assignment should be on a single line.

**Comment by justinmk** [comment]
> I tried to minimise the number of new lines, which seems to be a goal for this plugin.

Haha. It's not a goal per se, but a voluntary constraint which hopefully inspires creativity... like rhyme or metre in poetry, if you will forgive the pretentiousness...

> at the cost of readability:

tpope gets away with much worse ;) How about this:

```vim
    let cmd = a:cmd =~# '\V{}' ? a:cmd : (empty(a:cmd) ? '{}' : a:cmd.' {}')
```

**Comment by edkolev** [comment]
> pretentiousness

I had to look that up :D

> tpope gets away with much worse ;)

I remember looking at vim-jdaddy... scary stuff :)

The PR is updated. BTW I preserved the `"DWIM` comment

**Comment by davidsierradz** [comment]
I'm learning the `:Shdo` command, wasn't expecting the magical `{}` at the end, I want to archive something like:

`:Shdo touch %foo.bar`

This generate the next script:

`touch /home/user/folder/foo.bar 'somefile'`

Where 'somefile' is the file under the cursor, not deal breaking, I'm guessing its more common the current behavior.

Thanks

**Comment by arecarn** [comment]
I have also found myself in a number of similar situations as @davidsierradz, perhaps the old behavior without the implicit {} for a no argument Shdo could be enabled with a option?

**Comment by justinmk** [comment]
> Where 'somefile' is the file under the cursor

 `CTRL-L` (recent versions of Vim/Nvim) from the `:` prompt puts the current buffer line into the cmdline.

> perhaps the old behavior without the implicit {} for a no argument Shdo could be enabled with a option?

What's the point of using `:Shdo` if you don't want `{}` ?

**Comment by arecarn** [comment]
Didn't know about `CTRL-L` I'll have to try that out.

As for instances where you'd what to use `:Shdo` without {} is any time you care about what directory you are in, but don't care about the file under the cursor. e.g. 
* `mkdir dirname`
* `touch filename`
* `rm pattern*` (using a glob)
* `cp ../file .` (moving files relative to current directory)

**Comment by justinmk** [comment]
> time you care about what directory you are in, but don't care about the file under the cursor. 

Just use `%` . E.g.  

     :mkdir %dirname
