### ISSUE TITLE
Windows - Unable to open directory with #'s

### ISSUE THREAD

**Issue by AssailantLF** [justinmk/vim-dirvish#37]
I'm contributing to this [cool new repo](https://github.com/FreddieV4/DailyProgrammerChallenges/), and I'm unable to open the challenge directories for some reason, I suspect because of weird Windows escaping and the # symbol.

I've tested this on Linux with vim and gvim and they open just fine, but on Windows this error occurs:

    dirvish: invalid directory: 'C:\Git\DailyProgrammerChallenges\Intermediate Challenges\Challenge \#0012 [Intermediate]\'

**Comment by justinmk** [comment]
@AssailantLF Thanks for reporting. This is a tricky issue because of a [vim bug](https://github.com/vim/vim/issues/541), discussed here in regards to dirvish: https://github.com/neovim/neovim/issues/3912#issuecomment-167897305

**Comment by justinmk** [comment]
Actually in dirvish's case, I think I have a workaround.

**Comment by justinmk** [comment]
@AssailantLF Does everything seem to be working without regressions, for you?

**Comment by AssailantLF** [comment]
Yep, everything is working smoothly since your fix!
