### ISSUE TITLE
Support for adding new files/directories

### ISSUE THREAD

**Issue by airblade** [justinmk/vim-dirvish#38]
I use FileBeagle's `+` often to add a new file or directory.  Do you have any plans to build that capability into vim-dirvish?

**Comment by justinmk** [comment]
No, because `:e %foo` and `:!mkdir %foo` are trivial (in fact, what advantage does `+` have at all?). You also get tab-completion there should you need it, I presume FileBeagle's `+` does not do that. Nor nerdtree. If you want to create map you can do so like this:

```vim
    augroup my_dirvish_events
      autocmd!
      autocmd FileType dirvish nnoremap <buffer> + :edit %
    augroup END
```

**Comment by airblade** [comment]
Thanks for the quick response.

`+` has two advantages for me:

- brevity (though your map takes care of that)
- combines directory and file addition, e.g. `+foo/bar/baz/thingy.txt`, where `foo/` or below don't need to exist

I'll figure it out based on your mapping.  Thanks!

**Comment by justinmk** [comment]
> combines directory and file addition, e.g. +foo/bar/baz/thingy.txt

@airblade  That never occurred to me because I have this in my vimrc, which automatically creates `foo/bar/` as-needed when I `:edit foo/bar/baz.txt`:

    au BufWritePre,FileWritePre * silent! call mkdir(expand('<afile>:p:h'), 'p')

**Comment by airblade** [comment]
That's a nicer solution.  Thank you.
