### ISSUE TITLE
Alternate-file + hijack_netrw disabled = Buggy behavior

### ISSUE THREAD

**Issue by AssailantLF** [justinmk/vim-dirvish#39]
How to reproduce:

* Set `g:dirvish_hijack_netrw = 0`
* Open dirvish buffer
* Switch to alternate file via `:b#` or `CTRL-^`, and then switch back to dirvish.

The dirvish buffer has now become a become a netrw buffer, but it retains the dirvish mappings and leads to a lot of erroneous behavior.

**Comment by justinmk** [comment]
I was thinking about removing `g:dirvish_hijack_netrw` completely, because there is not much reason to have dirvish installed if you don't want it to take over `:edit <dir>` and `vim <dir>`.

> The dirvish buffer has now become a become a netrw buffer,

Yes, because by "not highjacking" netrw, we allowed it to respond to directory-like paths.

**Comment by AssailantLF** [comment]
I think I was using it on the contingency that dirvish had a bug (such as [issue 37](https://github.com/justinmk/vim-dirvish/issues/37)). However, I can just open an issue and restart vim with dirvish disabled, and it wouldn't be a problem. I can't really think of any other use besides that, so removing it makes sense in the long run.
