### ISSUE TITLE
How does this compare to VimFiler

### ISSUE THREAD

**Issue by rgrinberg** [justinmk/vim-dirvish#4]
I've read the description for this plugin and it seems like VimFiler already does everything that this plugin does. Did I miss something?

**Comment by justinmk** [comment]
VimFiler has many more features. Dirvish has almost no features :)

Only purpose of this plugin is to list files and go up/down. I use https://github.com/Shougo/unite.vim which does lots of fancy things, but sometimes I just want to browse directories. All of the full-featured directory browsers do more than I want, and get some details wrong, so those details are the point of this plugin.

Each line is an absolute path (hidden by syntax highlighting), so it's literally just a buffer that lists a bunch of paths (which you can then feed into other tools). Built-in Vim commands like `ctrl-w f` work on the lines as well.

Try `:Unite line` in a dirvish buffer: it lists the paths. Try `ggyG` and paste the paths into another buffer. 

I haven't tried VimFiler lately, but I would guess Dirvish also does a better job of not losing the alternate buffer (`#`), and always returning to the original buffer (`%`). I care about that sort of thing :P
