### ISSUE TITLE
Unexpected behaviour when using ctrlp from a dirvish buffer

### ISSUE THREAD

**Issue by qstrahl** [justinmk/vim-dirvish#43]
When invoking [ctrlp](/ctrlpvim/ctrlp.vim) from a dirvish buffer, it opens the selected file in a split rather than replacing the dirvish buffer. This is with default ctrlp settings.

**Comment by justinmk** [comment]
@qstrahl Repro'd. CtrlP does this for any non-empty `'buftype'` except for `"terminal"`. netrw does not set `buftype=nofile`, which is somehow not surprising. 

`buftype=nofile` is the right thing to do for a directory browser, so CtrlP should find a better heuristic. I get the idea of avoiding `quickfix` and maybe even `help` buffers, but the logic is too far-reaching beyond that.

This looks like the relevant line: https://github.com/ctrlpvim/ctrlp.vim/blob/dfd357ca9d8459a604ca26d3bb1f896b26398824/autoload/ctrlp.vim#L1746

**Comment by qstrahl** [comment]
Thanks for the detective work, @justinmk!
