### ISSUE TITLE
freeze when opening a file with existing swap file

### ISSUE THREAD

**Issue by nhooyr** [justinmk/vim-dirvish#44]
1. Open a random file
2. `killall -KILL nvim`
3. Try to open the file with dirvish
4. Freeze

Now you have to press escape to continue normally or if you press `<C-c>` then the buffer isn't read properly.

**Comment by justinmk** [comment]
Do you have any `au SwapExists` handlers or plugins like https://github.com/chrisbra/Recover.vim?

What vim version? I can't reproduce on nvim master nor vim 7.4.52.

The behavior I see is: when I select the file in dirvish, it shows the "swap exists" dialog asking whether to edit/delete/open readonly/etc.

**Comment by nhooyr** [comment]
neovim version:
```
NVIM v0.1.3-355-g6b22a74
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector
-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160317-11722-xxockh/build/config -I/tmp/neovim20160317-11722-xxockh/src -I/tmp/neovim20160317-11722-xxockh/
deps-build/usr/include -I/tmp/neovim20160317-11722-xxockh/deps-build/usr/include -I/tmp/neovim20160317-11722-xxockh/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160317-11722-xxockh/deps-build/usr/incl
ude -I/tmp/neovim20160317-11722-xxockh/deps-build/usr/include -I/tmp/neovim20160317-11722-xxockh/deps-build/usr/include -I/tmp/neovim20160317-11722-xxockh/deps-build/usr/include -I/usr/local/opt/gettext/i
nclude -I/usr/include -I/usr/include -I/tmp/neovim20160317-11722-xxockh/build/src/nvim/auto -I/tmp/neovim20160317-11722-xxockh/build/include
Compiled by nhooyr@aubble

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

Weird, it works fine with netrw. No `au SwapExists` handlers. I'll try and strip down my init.vim to see if I can locate the problem.

**Comment by justinmk** [comment]
@nhooyr Does netrw show the "swap exists" dialog at all?

**Comment by nhooyr** [comment]
@justinmk https://youtu.be/OaNTO2M21fg

I could reproduce on latest neovim master and I could not find anything in my init.vim that would cause this bug. It only happens on dirvish with neovim.

**Comment by justinmk** [comment]
> Now you have to press escape to continue normally or if you press `<C-c>` then the buffer isn't read properly

@nhooyr If you press "e" or "o" does it open?

**Comment by nhooyr** [comment]
@justinmk yes.

**Comment by nhooyr** [comment]
It has to do with `exe splitcmd fnameescape(path)` being in a try block here: https://github.com/justinmk/vim-dirvish/blob/master/autoload/dirvish.vim#L201

If I take it out of the try block, the swap menu is shown properly.

**Comment by justinmk** [comment]
@nhooyr Thanks. Just to be extra clear, the problem for you only happens in nvim, _not_ vim?

> If I take it out of the try block, the swap menu is shown properly.

Commenting [this block](https://github.com/justinmk/vim-dirvish/blob/master/autoload/dirvish.vim#L218-L219) is not enough--it must be removed from the `try` entirely?

**Comment by nhooyr** [comment]
@justinmk yes, and yes. Only in neovim and it must be removed from the `try` entirely.

**Comment by justinmk** [comment]
@nhooyr Seems like a redraw issue, which Neovim has suffered from lately. Does CTRL-L show the prompt when it "hangs"?

**Comment by nhooyr** [comment]
@justinmk nope.

**Comment by justinmk** [comment]
@nhooyr Since I couldn't reproduce it, could you let me know if it's fixed?

**Comment by nhooyr** [comment]
@justinmk yes its fixed. thank you!
