### ISSUE TITLE
Where is the cursor supposed to be after going up or down the file tree?

### ISSUE THREAD

**Issue by lydell** [justinmk/vim-dirvish#45]
I use vim installed from Ubuntu 16.04’s repositories and dirvish commit f3280a18254904e3fbebb0bfc4934ecc51a5c974.

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 08 2016 11:38:28)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.
```

I’ve tested with this .vimrc (using [vim-plug](https://github.com/junegunn/vim-plug)):

```viml
set nocompatible
call plug#begin('~/.vim/bundles')
Plug 'justinmk/vim-dirvish'
call plug#end()
```

I go upwards the file tree by pressing `-`, and downwards the file tree with `<cr>`.

After having pressed `<cr>`, I expect the cursor to be at the top of the buffer.
After having pressed `-`, I expect the cursor to be on the file or directory I came from.

Even if that’s not how Dirvish is supposed to work, I don’t understand how the cursor is placed. To me, it seems almost random.

Sometimes, the cursor is placed at the top – even when going upwards!
Sometimes, it is placed on some directory – but not necessarily the one I came from!

Anyone else experiencing this?

**Comment by justinmk** [comment]
Yes, this regressed recently. When going up, it should always be on the directory you're coming from. When going down, it is wherever your cursor last was in that buffer.

**Comment by lydell** [comment]
Correct cursor position is the most important when going _up,_ so let’s start there.

I’ve played around with it some more. Now, it seems to me that:

- The cursor is correctly placed when pressing `-` in a dirvish buffer.
- The cursor is placed at the top when pressing `-` in a regular buffer (when editing a file).

I tried this:

```diff
diff --git a/autoload/dirvish.vim b/autoload/dirvish.vim
index 7ad014a..a269f62 100644
--- a/autoload/dirvish.vim
+++ b/autoload/dirvish.vim
@@ -411,6 +411,9 @@ function! dirvish#open(...) range abort
   " Save lastpath when navigating _up_.
   if exists('b:dirvish') && d._dir ==# s:parent_dir(b:dirvish._dir)
     let d.lastpath = b:dirvish._dir
+    echo 'saved lastpath'
+  else
+    echo 'not saving lastpath ' . exists('b:dirvish')
   endif
 
   call s:save_state(d)
```

- When pressing `-` in a dirvish buffer, `saved lastpath` is echoed.
- When pressing `-` in a regular buffer, `not saving lastpath 0` is echoed.

So the main problem seems to be that `b:dirvish` doesn’t exist in regular buffers. Unfortunately, I don’t know how to take it form there. Hope this helps.

**Comment by justinmk** [comment]
@lydell That was helpful, thanks. Behavior should be much better now, LMK if you notice anything crappy.

**Comment by lydell** [comment]
Thanks. Works great now! :)

**Comment by airblade** [comment]
I found that sorting my dirvish buffer in a FileType autocommand reset the cursor to the first line (as expected when I thought about it).  The solution was to re-place the cursor afterwards:

```viml
  autocmd FileType dirvish let l=getline('.') |
        \ sort ir /^.*[^\/]$/ |
        \ keepjumps call search('\V\^'.escape(l,'\').'\$', 'cw')
```

Just thought I'd mention it in case anybody else stumbles across this in future.

**Comment by justinmk** [comment]
@airblade Instead of a global `g:l` variable, you could store it in `b:dirvish['foo']` instead.

**Comment by airblade** [comment]
@justinmk That's a good idea.  In my mind `l` was only used in that one autocmd but, as you point out, its scope is global – not ideal ;)

**Comment by chenoweth** [comment]
@airblade Nice solution! I may be wrong, but I don't think the `:keepjumps` modifier command. Because by default, `search()` doesn't add an entry in the jumplist. Only if you pass the `'s'` flag to it as a 2nd argument.

**Comment by airblade** [comment]
@chenoweth Thanks, I didn't appreciate that before.

**Comment by justinmk** [comment]
There is now a `g:dirvish_mode` option that avoids the need to place the cursor as mentioned in https://github.com/justinmk/vim-dirvish/issues/45#issuecomment-219991563. Try this:

    :let g:dirvish_mode = ':sort ir /^.*[^\/]$/'

See `:help g:dirvish_mode`.

**Comment by airblade** [comment]
@justinmk Nice.  Thanks for building this in.
