### ISSUE TITLE
"q" does nothing if dirvish is the first and only listed buffer

### ISSUE THREAD

**Issue by bounceme** [justinmk/vim-dirvish#48]
here are steps for reproducing

1. start vim with no arguments
2. press ```-```
3. press ```q```

**Comment by justinmk** [comment]
The plugin won't override an existing mapping:

https://github.com/justinmk/vim-dirvish/blob/c76e3d3eb607868490d8ad5ceb162a35b29fc062/plugin/dirvish.vim#L26

Did you check `:verbose map -`

**Comment by justinmk** [comment]
Oh, you mean `q` in particular. Discussed here: https://github.com/justinmk/vim-dirvish/issues/41#issuecomment-210157060

Question still remains: it will requires some extra logic/workarounds, and what's the benefit?

**Comment by bounceme** [comment]
```-``` is mapped to ```<plug> dervish```
```q``` in the dervish buffer is also mapped to the dervish close, but it won't do anything until you go to another dir

**Comment by bounceme** [comment]
oh, that is a good explanation. but the issue is that i do have buffers to switch to
```set viminfo+=%25
```

**Comment by bounceme** [comment]
maybe this is still intended, though, having the blank unnamed buffer that vim starts with reappear seems best to me

**Comment by bounceme** [comment]
i just tried using keepalt but that needs a file path,i guess the only way is by actually using a file in 'tmp'. that seems kind of strange how the start buffer works

**Comment by bounceme** [comment]
just if you are interested this is what nvi considers the start buffer,and the message when trying to save:
```/var/folders/h_/8vnjs37x69x6q9wcn8_qhhx00000gn/T//vi.juDoFF: 1 lines, 5 characters; File is a temporary; exit will discard modifications.```

**Comment by bounceme** [comment]
hey, so i am now just using this code to simulate the actual starting buffer behavior.
```
if !argc()
	autocmd vimrc vimenter * exe 'file ' . tempname() | set nobl
	nnoremap<buffer> - :Dirvish<cr>
end
```
however the map check will prevent the dervish up mapping being made

**Comment by justinmk** [comment]
@bounceme This problem doesn't seem to exist any more, I guess because of changes to `buf_close()`. Does it still happen for you?

**Comment by justinmk** [comment]
@bounceme This is fixed now.
