### ISSUE TITLE
Bug when starting Vim

### ISSUE THREAD

**Issue by rainerborene** [justinmk/vim-dirvish#5]
> Error detected while processing VimEnter Auto commands for "*":
> E216: No such group or event: FileExplorer *

If I disable this line Vim starts without any error message.
`Plug 'justinmk/vim-dirvish'`

**Comment by rainerborene** [comment]
This fix works for me:
```diff
diff --git a/plugin/dirvish.vim b/plugin/dirvish.vim
index 9fb447a..c8cac84 100644
--- a/plugin/dirvish.vim
+++ b/plugin/dirvish.vim
@@ -20,7 +20,9 @@ if get(g:, 'dirvish_hijack_netrw', 1)
   augroup dirvish_netrw
     au!
     " nuke netrw brain damage
-    autocmd VimEnter * au! FileExplorer *
+    if exists("#FileExplorer")
+      autocmd VimEnter * au! FileExplorer *
+    endif
     " netrw hijack (from EasyTree by Dmitry Geurkov <d.geurkov@gmail.com>)
     autocmd BufEnter * if !exists('b:dirvish') && isdirectory(expand('<amatch>'))
       \ | call dirvish#open(expand('<amatch>'))
```

**Comment by justinmk** [comment]
Thanks! And congratulations on not using netrw. (Unless you are using a recent version and the `FileExplorer` event was renamed?)

**Comment by rainerborene** [comment]
https://github.com/rainerborene/dotfiles/blob/master/.vimrc.bundles#L9
I suggest you do the same ;)

**Comment by justinmk** [comment]
Oh yeah, but I need to find a replacement for `gx` before I do that :P

**Comment by vheon** [comment]
> Oh yeah, but I need to find a replacement for gx before I do that :P
So I guess another plugin is coming? :P
