### ISSUE TITLE
EasyMotion symbols not displayed inside Dirvish

### ISSUE THREAD

**Issue by adambiggs** [justinmk/vim-dirvish#51]
In Dirvish buffers, EasyMotion symbols don't show up:
![screen shot 2016-05-26 at 11 30 46 am](https://cloud.githubusercontent.com/assets/857229/15585667/5344691e-2335-11e6-8ec3-7ae5e18d6d94.png)

It should look something like this:
![screen shot 2016-05-26 at 11 32 19 am](https://cloud.githubusercontent.com/assets/857229/15585711/9012dd44-2335-11e6-8958-1dcce50a8aeb.png)

**Comment by justinmk** [comment]
Could be a "conceal" conflict, assuming you're on a recent version of Vim and easymotion. What happens when you use easymotion in a help buffer?

**Comment by adambiggs** [comment]
Seems to work fine in help buffers:
![screen shot 2016-05-26 at 3 35 05 pm](https://cloud.githubusercontent.com/assets/857229/15592309/823666b0-2357-11e6-9a75-076b4734960d.png)

**Comment by justinmk** [comment]
It looks like you're using an easymotion invocation to label the start of each line? The first part of each line in a dirvish buffer is hidden by conceal. Try `:set conceallevel=0`, then what gets labeled? 

I'm not even sure if Vim has a way to search non-concealed text, so fixing this may require a change to Vim.

**Comment by adambiggs** [comment]
> The first part of each line in a dirvish buffer is hidden by conceal.

Ah that makes sense.

`:set conceallevel=0` fixed the issue... but also makes dirvish look pretty ugly. I guess there's not much I can do in this case.

**Comment by adambiggs** [comment]
I take it back! `let g:dirvish_relative_paths = 1` fixed the issue since there's nothing to conceal anymore. 😄

**Comment by adambiggs** [comment]
Sorry, have to take it back again... The above fix works in the project root directory, but as soon as i traverse into a subdirectory the issue comes back. 😢

**Comment by justinmk** [comment]
I am not aware of any Vim feature that allows a plugin to "skip" concealed (or otherwise non-displayed) characters. This is needed for plugins like easymotion and vim-sneak.

**Comment by adambiggs** [comment]
Would it be possible to add a non-concealed whitespace character in front of each line?

**Comment by justinmk** [comment]
Not sure what you mean. Whitespace won't help easymotion label anything. 

One potential approach would be to provide a mode that uses `:lcd` to root the directory, which would make `g:dirvish_relative_paths` do what you wanted. This would also potentially help with resolving https://github.com/justinmk/vim-dirvish/issues/19

**Comment by desjardinsm** [comment]
It's kind of a hacky workaround, but could you maybe do something with (even temporarily) setting `g:EasyMotion_startofline = 0` and moving the cursor `$T/`

**Comment by adambiggs** [comment]
Thanks for pointing me in the right direction @desjardinsm!

Everything seems to be working great after remapping easymotion with `$T/`:

```vim
let g:EasyMotion_startofline = 0

autocmd FileType dirvish
  \ map <buffer> <Leader>j $T/<Plug>(easymotion-j) |
  \ map <buffer> <Leader>k $T/<Plug>(easymotion-k)
```

**Comment by justinmk** [comment]
This works OK in vim-sneak since https://github.com/justinmk/vim-sneak/commit/c2cbcf789839d6d9f39a55b142479dcbc5a082f9 .

It should work in EasyMotion also. If it doesn't, file the bug with EasyMotion.
