### ISSUE TITLE
Mappings don't seem to work

### ISSUE THREAD

**Issue by rr-** [justinmk/vim-dirvish#52]
1. Open a file
2. `:Dirvish`
3. Dirvish opens up
4. `:set ft?` prints `dirvish`
5. ...and yet, pressing `<CR>`, `i` etc. works as if it was a plain buffer.

I tried removing all the plugins and bindings. The issue persists in Neovim and Vim alike.
Using `vim-plug`.

Manually setting `setf dirvish` on unrelated buffers does conceal absolute paths into relative ones so it works to certain extent, but the bindings are missing there too.

---

Tested with:

```console
rr-@tornado$ cat .testrc
call plug#begin()
Plug 'justinmk/vim-dirvish'
call plug#end()
rr-@tornado$ nvim -u .testrc
```

`:PlugStatus` shows only `vim-dirvish`.

**Comment by mhinz** [comment]
Can't reproduce this with neither Neovim (v0.1.5-565-gb463fb9) nor Vim (7.4.1967) and latest Dirvish.

**Comment by rr-** [comment]
No, it's just as if `ftplugin/dirvish.vim` wasn't ever loaded.

**Comment by desjardinsm** [comment]
And `:filetype plugin` is on?

**Comment by rr-** [comment]
That was it, I had to explicitly enable it with `filetype plugin on`. Curiously it didn't also work on empty vimrc as shown above; I thought it was on by default?...
Anyway, thanks.

**Comment by justinmk** [comment]
> Curiously it didn't also work on empty vimrc as shown above; I thought it was on by default?..

In neovim it is enabled by default since 0.1.4, _if_ your init.vim and plugins don't set it to something else during startup.
