### ISSUE TITLE
Color column highlight

### ISSUE THREAD

**Issue by khalidchawtany** [justinmk/vim-dirvish#55]
I have the following in my vimrc:
```vim
highlight! ColorColumn ctermbg=darkblue guibg=#E1340F guifg=#111111
call matchadd('ColorColumn', '\%81v', 100)
```
For some directories the above snippet causes **dirvish** to draw directories as follows:

![screen shot 2016-08-12 at 7 42 27 pm](https://cloud.githubusercontent.com/assets/1681606/17629816/1f2bcdca-60c5-11e6-90c2-3128a063c7fe.png)

If I move the cursor to errorwidget.h, this happens.
![screen shot 2016-08-12 at 7 42 43 pm](https://cloud.githubusercontent.com/assets/1681606/17629818/215515a2-60c5-11e6-9d05-aed9df4cf91c.png)

This is what I see, if I set conceallevel to 0.
![screen shot 2016-08-12 at 7 43 21 pm](https://cloud.githubusercontent.com/assets/1681606/17629829/30882960-60c5-11e6-8870-c6699f2dd589.png)

Is there anything I can do to solve this? I already have a hacky solution. However, I was wondering If it was something easy to fix ( Like invoking a user autocommand on dirvish_quit ).

**Comment by khalidchawtany** [comment]
Here is the hacky solution :(

```vim
"Prevent dirvish from mapping q
nmap  <Plug>(dirvish_quit_fake_map) <Plug>(dirvish_quit)

function! GetDirvishCloseSID()
  "Return highlight colors to normal, as we are leaving dirvish.
  highlight! ColorColumn ctermbg=darkblue guibg=#E1340F guifg=#111111

  return substitute(substitute(execute("map <Plug>(dirvish_quit)"), ".*:<C-U>","", 0), "<CR>", "", 0)
endfunction

augroup ColorColumn
  au!
"Use ''Normal'' color to highlight long lines in dirvish.
  autocmd FileType dirvish highlight! link ColorColumn Normal
        \| nnoremap <silent> <nowait> <buffer> q :silent! execute GetDirvishCloseSID()<cr>
augroup END
```

**Comment by justinmk** [comment]
`matchadd` is window-local. Save the `matchadd()` result in a window-local var:

    let w:my_colorcol_hi_id = matchadd('ColorColumn', '\%81v', 100)

Then 

```vim
augroup ColorColumn
  au!
  autocmd FileType dirvish silent! call matchdelete(w:my_colorcol_hi_id)
augroup END

**Comment by khalidchawtany** [comment]
Thanks :)
