### ISSUE TITLE
Can't figure out robust cursor-placement-after-sorting logic

### ISSUE THREAD

**Issue by chiphogg** [justinmk/vim-dirvish#58]
dirvish's philosophy for customizing sorting is "do it yourself with an `autocmd`".  Unfortunately, `sort` leaves the cursor at the top of the file, which breaks the feature that "pressing `-` leaves you on the name of the current file".
#45 provides a nice fix.  After [I implemented it](https://github.com/chiphogg/dotfiles/commit/bc3bb2d0631273f500f8204b2c2a4ee20f31beee), pressing `-` correctly placed me on the current filename.

While this fixes the behaviour when going _up_, it breaks the behaviour going _down_.  Namely, I expect the cursor to be at the first line of the buffer when I hit `<Enter>` on a directory.  Instead, the cursor ends up on the line that _was_ at the top of the file, _before_ sorting.  This is really jarring, and almost as bad as `-` not working right.

I am not sure how to fix this robustly, except by introducing custom sorting (or even a custom `autocmd`, to be run between buffer content generation and cursor placement) as a first-class dirvish feature.  I get the feeling there's a lot of demand for custom sorting, but I suspect that making it first-class runs counter to your philosophy for the plugin.  Do you have any advice?

**Comment by justinmk** [comment]
Filtering and sorting are definitely popular requests. The philosophy is not intended to be dogmatic, rather it's a sense that solving the hitherto observed quirks, if possible, will be much more valuable because it will provide "best practices" for extending the plugin beyond whatever might be built-in.

A potential compromise is to provide richer events and/or context flags.

> a custom autocmd, to be run between buffer content generation and cursor placement

Yes, something like that.

**Comment by justinmk** [comment]
The new `g:dirvish_mode` feature should solve this nicely (let me know if not). Try this:

    :let g:dirvish_mode = ':sort'

`g:dirvish_mode` takes a couple options or an arbitrary ex command. See `:help g:dirvish_mode`.

**Comment by chiphogg** [comment]
This works terrifically well for sorting folders ahead of everything else.  Thanks!

```vim
let g:dirvish_mode = ':sort! | :sort! r /[/]$/'
```
