### ISSUE TITLE
nvim and `dirvish: E37: No write since last change`

### ISSUE THREAD

**Issue by lbonn** [justinmk/vim-dirvish#59]
It looks that the fix for #47 (#53) does not work with nvim.

I use the current master (6bc12c73cfdc841f4577f424bc4bdeca79d6f4d2) and the behavior is exactly the same as described in the original issue. It works fine when I use vim with the same settings, though.

EDIT: by the way, here is my neovim version `NVIM v0.1.6-36-g0ade1bb`. I guess that it's probably because `win_findbuf` was not ported yet to neovim but I did not check this.

**Comment by lbonn** [comment]
Indeed, the patch that introduces this command (7.4.1558) was not merged in neovim (see https://neovim.io/doc/reports/vimpatch/). I'll raise the issue to them.

Sorry about the noise.

**Comment by justinmk** [comment]
@lbonn I'll merge 1558 to nvim now.

**Comment by justinmk** [comment]
@lbonn I'll merge 1558 to nvim now. (Or were you planning to merge it?)

**Comment by lbonn** [comment]
@justinmk thanks! That's fine by me, go ahead.

**Comment by justinmk** [comment]
In nvim latest: https://github.com/neovim/neovim/pull/5333
