### ISSUE TITLE
dirvish takes up whole page when opened from a split

### ISSUE THREAD

**Issue by Pyrohh** [justinmk/vim-dirvish#6]
To reproduce:
- Open a file: `nvim file` (`:e file` from nvim causes the issue too)
- Make a split based on the same buffer: `:vs` or `:sp` (both seem to cause the issue)
- Open a folder: `:e ~/.nvim`
- There should now be only one window (dirvish), as opposed to two (one for `file`, one for dirvish)

**Comment by justinmk** [comment]
Good catch, thanks. I didn't like that `:bwipe` anyway. I had previously given up on `:file` but it actually does exactly what we want for this workaround (keeps the bufnr, changes the name, preserves splits).
