### ISSUE TITLE
:Shdo leaves temp files

### ISSUE THREAD

**Issue by bounceme** [justinmk/vim-dirvish#60]
is that setting made on purpose with this plugin? I see new temp files for every new dervish buffer

**Comment by justinmk** [comment]
Files, or buffers? Each directory you open is its own buffer, intentionally. And the same buffer for the same directory is reused.  They are unlisted.

This is critical for the jump list, caching, and general reasoning. It also makes the code very simple. 

Directory browser plugins that don't do this are instead storing similar data in private dictionaries, so it's not like they save memory. 

If you're worried about high buffer numbers I'd say don't be, that's a Vim usage antipattern :)

**Comment by bounceme** [comment]
Does `nobuflisted` make the buffer inaccessible for viml? it is just annoying for people who use the `:ls` command to have a huge list of giant temp file paths rather than important files

**Comment by bounceme** [comment]
Hey, you were right about the regular dervish buffers being unlisted, it's the `shdo` temples that are listed

**Comment by bounceme** [comment]
How about adding :bd to the Z! mapping?

**Comment by justinmk** [comment]
My thought was, users might want to work with the `:Shdo` script for more than just one `Z!` invocation. Or if the `Z!` invocation didn't do what was expected, then the user might want to edit and try again.

`dirvish#shdo()` does `setlocal nobuflisted`, but Vim re-lists the buffer under certain conditions. `setlocal bufhidden=delete` has the same quirk, but we can force it in ShellCmdPost (irrelevant for `:terminal`, currently).

**Comment by justinmk** [comment]
Should be good now, let me know if not.

**Comment by bounceme** [comment]
Yes! good now. maybe bufhidden=delete ? wouldn't that allow for someone to <c-o> back if they needed?

**Comment by justinmk** [comment]
>  wouldn't that allow for someone to `<c-o>` back if they needed?

Yes, but then the buffer will be listed. And the buffer-local mappings won't be there. 

I chose `wipe` because that's what fugitive commit (not status) buffers do, and these temporary shell scripts seem roughly equivalent. Hmmm...

**Comment by bounceme** [comment]
Oh, i see. `h special-buffers`  has a few examples given for 'abstract' buftypes
