### ISSUE TITLE
bufread

### ISSUE THREAD

**Issue by bounceme** [justinmk/vim-dirvish#61]
the bufread event occurs when you use the Dirvish command, surprisingly with the file already opened. This can be slow because of user autocmds and also the time needed to reread the file

**Comment by justinmk** [comment]
What's the value of `set hidden?` for you?

**Comment by bounceme** [comment]
no hidden

**Comment by justinmk** [comment]
Does it happen with `set hidden`?

**Comment by bounceme** [comment]
not with hidden. also the dervish buffer seems to open smoother with `set hidden`

**Comment by bounceme** [comment]
did you fix this? I am not experiencing this anymore

**Comment by justinmk** [comment]
@bounceme are you using `set hidden`? I'll look at this now.

**Comment by bounceme** [comment]
sorry again, yes: set hidden
