### ISSUE TITLE
E94 when starting vim on a directory

### ISSUE THREAD

**Issue by tertium** [justinmk/vim-dirvish#64]
Starting vim on a directory produces the following error:

% vim ~/tmp
Error detected while processing function dirvish#open[36]..<SNR>35_do_open[58]..<SNR>35_set_altbuf:
line    2:
E94: No matching buffer for -1

Presumably, this is related to the fact that there is no previous buffer when we open Dirvish.

**Comment by justinmk** [comment]
@tertium Thanks for reporting!

**Comment by tertium** [comment]
Thanks for the lightning-fast fix!

**Comment by tertium** [comment]
It seems that now set_altbuf() will return if has('patch-7.4.605') is true without executing the rest of the function. Is this intentional?

**Comment by justinmk** [comment]
It returns after `let @# = a:bnr`, yes, that's intentional (forgotten in the previous commit).

**Comment by tertium** [comment]
I have another question about starting vim on a directory. The Dirvish buffer created in this case (or with :e <directory>) is listed and is not deleted when hidden. This is contrary to the behaviour of Dirvish buffers opened with :Dirvish. Is this also intentional?

**Comment by justinmk** [comment]
It's an edge case to allow q to work. The first buffer in Vim is special.
