### ISSUE TITLE
does not show the CWD when &title is set

### ISSUE THREAD

**Issue by tertium** [justinmk/vim-dirvish#66]
vim 8.0 0049, run in a terminal with "set title", shows the empty string as the file name when the Dirvish buffer is entered. For example, this is the terminal title when I do :Dirvish /tmp
 = (/)
I would expect the name of the current directory to appear to the left of the "=" status flag.

**Comment by justinmk** [comment]
Dirvish doesn't modify CWD. What does `:pwd` show?

**Comment by justinmk** [comment]
Ok, reproduced like this:

    vim -N -u NORC +'set title' +'set rtp+=~/.local/share/nvim/bundle/vim-dirvish' +'runtime plugin/dirvish.vim'

If I do `:Dirvish /foo/bar/`, the title shows `/foo`. Isn't that decision up to Vim? The buffer name is most definitely `/foo/bar/`, what can Dirvish do about what Vim decides to show in `'titlestring'`?

**Comment by tertium** [comment]
Sorry, my wording was misleading. I did not mean that the title should show the real current directory. The first component of the default title string is the filename being edited (according to :help title), and I would expect it to coincide with the name of the directory that Dirvish is showing. That is, after :Dirvish /tmp, I would expect the title to be
tmp/ = (/) - VIM
Instead, I see
 = (/) - VIM
with a space instead of the directory name.

**Comment by justinmk** [comment]
Yeah, see my updated comment above. Normally Vim tries to show the file name followed by the directory. But its logic is kind of dumb, if the buffer name _is_ a directory, it will show _nothing_ for the filename, and yet still chops off the file segment of the full buffer name.

**Comment by tertium** [comment]
Well, if I don't start Dirvish (and I don't have netrw either), than Vim does the right thing:
% vim ~/foo/bar
shows the title
bar (~/foo) - VIM
and a warning on the last line `"foo/bar" is a directory'.

So, I'd say, Dirvish does something to disrupt the title string.

**Comment by justinmk** [comment]
yes, because `~/foo/bar` doesn't end in a slash. Dirvish intentionally has deterministic buffer names: the buffer is guaranteed to always be absolute, and always end in a slash.

I don't think `bar (~/foo)` is really what one is looking for, anyways. It is, again, an accident of Vim's broken logic. The logic _could_ be fixed--there is zero reason it should show a blank filename _and_ truncate the last segment.

**Comment by tertium** [comment]
Okay, I played with :file a bit, and you are right, it's Vim's own glitch: ":file foo/bar" sets the title correctly, and ":file foo/bar/" does the stupid thing. I agree with closing this bug as invalid.

One last question though: do you expect anything to break if I change the Dirvish's policy and remove the trailing slash from the buffer name (say, with an appropriate autocommand)?

**Comment by justinmk** [comment]
If you merely rename the dirvish buffer, dirvish still work. If you change it internally, things will break. Would be better to fix Vim itself.
