### ISSUE TITLE
RFC: "project drawer"-style display

### ISSUE THREAD

**Issue by zandrmartin** [justinmk/vim-dirvish#68]
I've written some code to make Dirvish behave _a bit_ like a project drawer - essentially just opening itself in a 35-column split and closing itself when opening a file. (I personally never want to use an entire full-width buffer for a Dirvish listing.) This is the entirety of the code:
```vim
nmap <C-o> <Plug>(dirvish-toggle)
nnoremap <silent> <Plug>(dirvish-toggle) :<C-u>call <SID>dirvish_toggle()<CR>

function! s:dirvish_toggle() abort
  let l:last_buffer = bufnr('$')
  let l:i = 1
  let l:dirvish_already_open = 0

  while l:i <= l:last_buffer
    if bufexists(l:i) && bufloaded(l:i) && getbufvar(l:i, '&filetype') ==? 'dirvish'
      let l:dirvish_already_open = 1
      execute ':'.l:i.'bd!'
    endif
    let l:i += 1
  endwhile

  if !l:dirvish_already_open
    35vsp +Dirvish
  endif
endfunction

function! s:dirvish_open() abort
  let l:line = getline('.')
  if l:line =~? '/$'
    call dirvish#open('edit', 0)
  else
    call <SID>dirvish_toggle()
    execute 'e '.l:line
  endif
endfunction

augroup dirvish_commands
  autocmd!
  autocmd FileType dirvish call fugitive#detect(@%)
  autocmd FileType dirvish nnoremap <silent> <buffer> <C-r> :<C-u>Dirvish %<CR>
  autocmd FileType dirvish unmap <silent> <buffer> <CR>
  autocmd FileType dirvish nnoremap <silent> <buffer> <CR> :<C-u> call <SID>dirvish_open()<CR>
  autocmd FileType dirvish setlocal nonumber norelativenumber statusline=%F
  autocmd FileType dirvish silent! keeppatterns g@\v/\.[^\/]+/?$@d
  autocmd FileType dirvish execute ':sort r /[^\/]$/'
augroup END
```
I'd be glad to clean this up (remove unrelated sorting etc) and do a PR if this is something you'd be interested in merging as a `let g:dirvish_project_drawer_view = 1`-style option. But I also completely understand if you don't want this kind of thing in Dirvish proper.

**Comment by justinmk** [comment]
Thanks.

> essentially just opening itself in a 35-column split and closing itself when opening a file.

I don't get the purpose of this. Dirvish takes care to restore the alternate and original buffer, so if you want to close the project drawer after opening a file, what's the point of having a project drawer?

For a long-lived "project drawer"--which one wouldn't want to close--"preview" mappings should serve that purpose nicely. https://github.com/justinmk/vim-dirvish/pull/65

**Comment by zandrmartin** [comment]
The purpose for me is just keeping the Dirvish buffer on the side as its own thing. I think of it like a file open dialog more than a project drawer, I suppose. As you pointed out, the automatic closing part kind of negates the idea of it being a project drawer anyway.

Anyway, sorry for the noise, and thanks for the consideration!

**Comment by marlon-schroder** [comment]
> I've written some code to make Dirvish behave _a bit_ like a project drawer - essentially just opening itself in a 35-column split and closing itself when opening a file. (I personally never want to use an entire full-width buffer for a Dirvish listing.) This is the entirety of the code:
> 
> ```viml
> nmap <C-o> <Plug>(dirvish-toggle)
> nnoremap <silent> <Plug>(dirvish-toggle) :<C-u>call <SID>dirvish_toggle()<CR>
> 
> function! s:dirvish_toggle() abort
>   let l:last_buffer = bufnr('$')
>   let l:i = 1
>   let l:dirvish_already_open = 0
> 
>   while l:i <= l:last_buffer
>     if bufexists(l:i) && bufloaded(l:i) && getbufvar(l:i, '&filetype') ==? 'dirvish'
>       let l:dirvish_already_open = 1
>       execute ':'.l:i.'bd!'
>     endif
>     let l:i += 1
>   endwhile
> 
>   if !l:dirvish_already_open
>     35vsp +Dirvish
>   endif
> endfunction
> 
> function! s:dirvish_open() abort
>   let l:line = getline('.')
>   if l:line =~? '/$'
>     call dirvish#open('edit', 0)
>   else
>     call <SID>dirvish_toggle()
>     execute 'e '.l:line
>   endif
> endfunction
> 
> augroup dirvish_commands
>   autocmd!
>   autocmd FileType dirvish call fugitive#detect(@%)
>   autocmd FileType dirvish nnoremap <silent> <buffer> <C-r> :<C-u>Dirvish %<CR>
>   autocmd FileType dirvish unmap <silent> <buffer> <CR>
>   autocmd FileType dirvish nnoremap <silent> <buffer> <CR> :<C-u> call <SID>dirvish_open()<CR>
>   autocmd FileType dirvish setlocal nonumber norelativenumber statusline=%F
>   autocmd FileType dirvish silent! keeppatterns g@\v/\.[^\/]+/?$@d
>   autocmd FileType dirvish execute ':sort r /[^\/]$/'
> augroup END
> ```
> 
> I'd be glad to clean this up (remove unrelated sorting etc) and do a PR if this is something you'd be interested in merging as a `let g:dirvish_project_drawer_view = 1`-style option. But I also completely understand if you don't want this kind of thing in Dirvish proper.

Ohh man, I really liked this, thanks for sharing!
