### ISSUE TITLE
error in docs 

### ISSUE THREAD

**Issue by nhooyr** [justinmk/vim-dirvish#69]
https://github.com/justinmk/vim-sneak/blob/f00084c6f9e28e8836c3e4b5dc7e255098843a10/doc/sneak.txt#L36

Wouldn't you need to press `'ssi'` again?

**Comment by nhooyr** [comment]
Oh, you have to press `'s'` and then enter.

**Comment by nhooyr** [comment]
Oh my god, I opened it in the wrong repository LOL...

I had to set `let g:sneak#s_next = 1`, perhaps the docs should be clarified?

**Comment by justinmk** [comment]
Ok, mind reopening in the other repo?
