### ISSUE TITLE
Why is DirvishPathTail defined in plugin/dirvish.vim?

### ISSUE THREAD

**Issue by lifepillar** [justinmk/vim-dirvish#71]
Is there a valid reason for DirvishPathTail being defined in the main plugin file rather than in `syntax/dirvish.vim`? I ask because logically a highlight command belongs to a syntax file. Also, that single command makes Dirvish's startup time 5–10x slower.

**Comment by justinmk** [comment]
So that is can be overridden by the user, I guess. Patch welcome

**Comment by lifepillar** [comment]
See https://github.com/justinmk/vim-dirvish/pull/72.
