### ISSUE TITLE
Can't run script in fish shell

### ISSUE THREAD

**Issue by azure-satellite** [justinmk/vim-dirvish#73]
Trying to execute the resulting script from `Shdo` using fish shell on OS X fails with

```
exec: Exec format error
The file '{tmpfile}' is marked as an executable but could not be run by the operating system.
```

Specifying the shell after a shebang solves it. Maybe `$SHELL` can be used or `/bin/sh` as a fallback?

**Comment by justinmk** [comment]
> Maybe $SHELL can be used or /bin/sh as a fallback?

Fall back under what conditions? What is `:set shell` ? All `Z!` does is call `:!`, it's assumed you've configured `'shell'`, `'shellcmdflag'`, etc appropriately.

**Comment by azure-satellite** [comment]
`:!` works as expected.
`'shell'` == `$SHELL` == `/usr/bin/local/fish` and `shellcmdflag` == `-c`

The problem is that the executable file produced by `Shdo` itself is run with `:!`, which fish doesn't like.

This is what I'm talking about https://wiki.archlinux.org/index.php/Talk:Fish.

**Comment by justinmk** [comment]
> :! works as expected.

How is that possible? `:!%` in the script buffer works for you?

**Comment by azure-satellite** [comment]
No I meant that `:!` (not `:!%` on the script buffer) works for me. As in `:!cat foo`.

The last commit fixes it indeed. Thank you very much!
