### ISSUE TITLE
Honor 'suffixes' / provide a way to exclude files

### ISSUE THREAD

**Issue by blueyed** [justinmk/vim-dirvish#74]
I'd like to exclude `*.pyc` files, but it seems like there is no way to do that?

The `glob()` being used to list the files uses the `nosuf` option (https://github.com/justinmk/vim-dirvish/blob/90dcfebf8444d8423d86819c9841c11b7a783a4d/autoload/dirvish.vim#L37).

**Comment by justinmk** [comment]
This is definitely a good idea.

- improves performance a bit by avoiding a sort()
- aligns with the plugin's theme: conforming to Vim's conventions
- is actually pretty useful

One disadvantage is that any files in 'wildignore' will be missing, that will be a bit annoying. So there needs to be a map that can toggle this.

```diff
diff --git a/autoload/dirvish.vim b/autoload/dirvish.vim
index 1b7525330955..aa0ee5e8eb0f 100644
--- a/autoload/dirvish.vim
+++ b/autoload/dirvish.vim
@@ -34,11 +34,11 @@ endfunction
-
 if v:version > 703
 function! s:globlist(pat) abort
-  return glob(a:pat, 1, 1)
+  return glob(a:pat, 0, 1)
 endfunction
 else "Vim 7.3 glob() cannot handle filenames containing newlines.
 function! s:globlist(pat) abort
-  return split(glob(a:pat, 1), "\n")
+  return split(glob(a:pat, 0), "\n")
 endfunction
 endif
-
@@ -51,9 +51,9 @@ function! s:list_dir(dir) abort
-
   if get(g:, 'dirvish_relative_paths', 0)
       \ && a:dir != s:parent_dir(getcwd()) "avoid blank CWD
-    return sort(map(paths, "fnamemodify(v:val, ':p:.')"))
+    return map(paths, "fnamemodify(v:val, ':p:.')")
   else
-    return sort(map(paths, "fnamemodify(v:val, ':p')"))
+    return map(paths, "fnamemodify(v:val, ':p')")
   endif
 endfunction
```

**Comment by justinmk** [comment]
'suffixes' and 'wildignore' are now applied by default, and `g:dirvish_mode` gives full control if desired. 

@blueyed Thanks for the suggestion!
