### ISSUE TITLE
conceal breaks sometimes

### ISSUE THREAD

**Issue by nhooyr** [justinmk/vim-dirvish#75]
1. `Dirvish`
2. `split | Dirvish ..`
3. `q`
4. Now the open Dirvish window should look like:

![screen shot 2017-02-19 at 10 10 27 pm](https://cloud.githubusercontent.com/assets/10180857/23110556/3cef68aa-f6f0-11e6-8b01-e678cf63f11f.png)

**Comment by justinmk** [comment]
Can't reproduce. Tried this:

```
vim -N -u NORC +'set rtp+=~/.local/share/nvim/bundle/vim-dirvish' +'runtime plugin/dirvish.vim'
Dirvish
split | Dirvish ..
q
```
