### ISSUE TITLE
NERDTree will hijack dirvish when close split window

### ISSUE THREAD

**Issue by markwu** [justinmk/vim-dirvish#77]
NERDTree will hijack dirvish when close split window, I have no idea why it happened.

But, this can be fixed if I clean `NERDTreeHijackNetrw` auto command group in `vim-dirvish/plugin/dirvish.vim`

```vim
...
autocmd VimEnter * silent! au! FileExplorer *
autocmd VimEnter * silent! au! NERDTreeHijackNetrw *
...
```

**Comment by justinmk** [comment]
If multiple directory-browser plugins are installed, which one should only one plugin can show it. 

I guess you might want different dir-browser plugins, and whichever one appears last in 'runtimepath' takes precedence for directory buffers. So I'll make your suggested change, thanks.

**Comment by markwu** [comment]
Yes, I use dirvish in most case. But sometimes I need to navigate my files by tree view. That's why I install both of them.
