### ISSUE TITLE
Add a syntax rule to dim files according to suffixes

### ISSUE THREAD

**Issue by shym** [justinmk/vim-dirvish#81]
One feature I like in vinegar is the fact that files matching 'suffixes' are highlighted in a dimmed way.
Could this be added to dirvish?

**Comment by justinmk** [comment]
Is that a nwtrw feature or vinegar?

**Comment by shym** [comment]
The syntax rule netrwSuffixes is set by vinegar (very [last lines](https://github.com/tpope/vim-vinegar/blob/master/plugin/vinegar.vim#L122)).

**Comment by justinmk** [comment]
Note that dirvish by default sorts according to suffixes option, so lower priority already are towards the bottom.

**Comment by shym** [comment]
I noticed. I still liked the simple visual feedback of the separation.
I’m fine with just putting

```vim
highlight default link dirvishSuffixes SpecialKey
autocmd FileType dirvish execute 'syntax match dirvishSuffixes =[^/]\+\%('.join(map(split(&suffixes, ','), 'substitute(escape(v:val, ".$~"), "*", ".*", "g")'), '\|').'\)='
```

in my `.vimrc`. This is probably not really robust though.

**Comment by justinmk** [comment]
Thanks for the hints. I think it does what you want now.
