### ISSUE TITLE
Sort lines according to LC_COLLATE

### ISSUE THREAD

**Issue by sstallion** [justinmk/vim-dirvish#83]
Is it possible to sort lines according to `LC_COLLATE`? In my case I prefer using C formatting; that is directories are listed first in lexical order (i.e. dotfiles precede regular files). I haven't had much luck emulating this using the `:sort` command. Any help is appreciated!

**Comment by justinmk** [comment]
No idea, but `:sort` would be the way to do it. Then store than in `g:dirvish_mode` and it will be applied always.
