### ISSUE TITLE
fugitive commands don't work in dirvish?

### ISSUE THREAD

**Issue by sodiumjoe** [justinmk/vim-dirvish#88]
when I try `:Gstatus` in a dirvish buffer, I get:

```
E492: Not an editor command: Gstatus
```

**Comment by mhoogendoorn** [comment]
The README has an example of enabling `:GStatus` using an autocmd. Can also add it to `g:dirvish_mode`:

    let g:dirvish_mode = ':call fugitive#detect(@%)'

**Comment by justinmk** [comment]
Fugitive by default doesn't activate itself for directory buffers. You can tell fugitive to activiate itself via `fugitive#detect()`. The dirvish FileType event is the conventional way to initialize dirvish things. The buffer name will already be correct when that event fires, so `@%` will contain the path that fugitive expects.

Add this to your vimrc:

    autocmd FileType dirvish call fugitive#detect(@%)

Note: Dirvish doesn't enable fugitive by default, though I have been tempted ...
