### ISSUE TITLE
group-directories-first sorting

### ISSUE THREAD

**Issue by mkoskar** [justinmk/vim-dirvish#89]
So I wanted the sorting similar to `$ ls -la --group-directories-first`.
In the doc/FAQ there is a mention about:

```
Sort folders at the top:
:sort r /[^\/]$/
```

I believe it's not really working example. In fact afaik it will sort only non-dir lines (so they end up on bottom of the buffer) and by the last character of the filename.

I've come up with `let dirvish_mode = ':sort | sort ,^.*/,'` which does that. I don't particularly like necessity of 2 sorts but can't see the way around it unless dirvish first returns `.` entries and rest afterwards (speaking of the 2 globs in `function! s:list_dir(dir) abort`).

**Comment by justinmk** [comment]
`let dirvish_mode = ':sort ,^.*/,' ` looks better to me. The first `:sort` isn't needed unless you really care about dot-files being sorted at the top (why...?).

>  I don't particularly like necessity of 2 sorts but can't see the way around it unless dirvish first returns . entries

We could have some option where `g:dirvish_mode=':foo'` is combined with `glob(...,1)` behavior. But then `glob()` is doing the 'suffixes' sort internally anyway.

Grouping things requires work :) If performance is a concern, don't group things. Probably you won't notice the difference except on directories with thousands of items.

**Comment by mkoskar** [comment]
I concede that having `.` dirs first is more than anything personal preference and some people might like it just the opposite way. There could be an option that would determine the order of glob calls, so first return `.` files and then the rest vs. opposite. That would let me go by with only `:sort ,^.*/,`, but idk if it's worth the effort.

I mainly wanted to highlight that FAQ entry which seem erroneous and probably warrants editing. Took me some time to get the sorting expression right so this might help others I suppose. All in all it at least got me to understand `:sort` the way I didn't before ;).

**Comment by justinmk** [comment]
Yes, thanks for mentioning it! The improved pattern is better.

**Comment by virus-found** [comment]
So is the best and only way to use `let dirvish_mode = ':sort | sort ,^.*/,'` to get the midnight-commander-like sort?

**Comment by mkoskar** [comment]
@virus-found That's what I've settled with.

**Comment by chunkhang** [comment]
I settled with `let g:dirvish_mode = ':sort | sort ,^.*[^/]$, r'`.

```
.circleci/
.git/
config/
controllers/
grpc/
hooks/
migrations/
models/
node_modules/
test/
utils/
.dockerignore
.gitignore
.tags
Dockerfile
index.js
package-lock.json
package.json
pnpm-lock.yaml
```

**Comment by nomasprime** [comment]
@chunkhang why this over `:sort | sort ,^.*/,`?

**Comment by nomasprime** [comment]
@justinmk you have a recommendation on this?

**Comment by justinmk** [comment]
> @justinmk you have a recommendation on this?

whatever is in `:help dirvish`

**Comment by nomasprime** [comment]
Checked but doesn't cover this.

**Comment by justinmk** [comment]
@nomasprime if you are asking about sorting in some way not already covered by the FAQ or the above discussion, then it should be in a new issue with a specific question.

**Comment by andis-sprinkis** [comment]
```lua
vim.g.dirvish_mode = ':sort i | sort ,^.*[^/]$, ri'
```

Hidden first, lowercase first, directories and files grouped separately.

```
.a/
.A/
.b/
a/
A/
b/
.a
.A
.b
a
A
b
```
