### ISSUE TITLE
how to remap?

### ISSUE THREAD

**Issue by plexigras** [justinmk/vim-dirvish#95]
```vim
autocmd FileType dirvish nmap <buffer>, <Plug>(dirvish_arg)
autocmd FileType dirvish xmap <buffer>, <Plug>(dirvish_arg)
```

this doesnt work

https://github.com/justinmk/vim-dirvish/blob/master/ftplugin/dirvish.vim#L6-L9

**Comment by justinmk** [comment]
Works for me. I added those lines to my vimrc:

```
autocmd FileType dirvish nmap <buffer>, <Plug>(dirvish_arg)
autocmd FileType dirvish xmap <buffer>, <Plug>(dirvish_arg)
```

And restarted vim. `,` works, and `.` is not mapped.

What doesn't work for you?

**Comment by plexigras** [comment]
so it works for you but not for me thats weird any ideas why that could be?

**Comment by justinmk** [comment]
Maybe related to the order of things in your config, e.g. if you use a plugin manager, make sure the the plugin is added before you add the autocmds.

Also your report of "doesn't work" isn't precise. Does "doesn't work" mean `,` isn't mapped at all? What is `,` mapped to, then?

https://github.com/justinmk/vim-dirvish/blob/master/ftplugin/dirvish.vim#L6-L9 only decides whether `.` is mapped.
