### ISSUE TITLE
Avoid Scrolling Window

### ISSUE THREAD

**Issue by Asheq** [justinmk/vim-dirvish#99]
When switching back to a buffer (e.g. with `C-^` and `:bn` and family, etc.), Vim tries to scroll whatever line the cursor was on last to the center of the window. I find this behavior extremely disorienting, so I use the code in the following link to just leave the window position exactly the way it was.

http://vim.wikia.com/wiki/Avoid_scrolling_when_switch_buffers

This code relies on the `BufEnter` and `BufLeave` autocommands. However, it seems that opening Dirvish does not invoke these autocommands. As a test, open Dirvish and immediately close it with `q`. Observe how Vim will still try to scroll the window so the cursor line is in the center of the window.

Thanks for your help, and for creating this awesome plugin!

**Comment by justinmk** [comment]
> This code relies on the BufEnter and BufLeave autocommands. However, it seems that opening Dirvish does not invoke these autocommands

By "these autocmmands", you mean only `BufEnter`? When would `BufLeave` be fired on `q` (or please give such an example)?

**Comment by Asheq** [comment]
The VimScript in the link I posted essentially works like this:

1. When you leave a buffer (detected by the `BufLeave` autocommand), it saves the window state using `winsaveview()`.
2. When you enter a buffer (detected by `BufEnter`), it checks if there is a window state saved for that buffer and if so, restores it using `winrestview(saved_window_state_for_buffer)`.

The VimScript works as expected when you switch back to a buffer using `C-^`, for instance. (Give it a try; I highly recommend it for everyone, to avoid being disoriented because of the default way that Vim tries to scroll a window when switching back to a buffer.)

The VimScript does not work, however, when using Dirvish to switch buffers. I believe this is because opening Dirvish doesn't cause `BufLeave` to fire. What this effectively means is that when you call :Dirvish while inside a buffer, the buffer's window state is not saved. Furthermore, if you close Dirvish with `q` to return to the original buffer, a restore is never attempted because `BufEnter` never fires (not that it matters since there is no state to restore anyway)

**Comment by justinmk** [comment]
`BufEnter` should fire now. `BufLeave` is still spotty.
